# Analysis

##Scope of Analysis:
One of the first goals was to get an overall look at the data available for exploration, once it was connected in a relational way.  The initial strategy involved attempting to condense and aggregate details.  An issue that was understood and would prove to be a significant challenge was how granular the formulary data was.  An extensive analysis of the formulary data was required just to determine which descriptive statistics would best relate to the census data.  Another key consideration was trying to determine which medications to focus on.  It was not feasible to attempt to evaluate all 6000 medications in the formulary across all plans and contracts.  An appropriate solution was to focus on one or a few medications within the formulary.  The addition of the CMS spending data proved to be invaluable.  This data proved to be simple and well-structured, allowing for quick analysis.  Many approaches were tested.  The most robust and informative version of this exploration was the result of combining the spending data from Part B, Part D, and Medicaid.  This allowed for the identification of high-impact drugs that would warrant exploration.  Our team created lists of the top 10 and top 25 drugs by spending across these three pools of coverage.  Additionally, beneficiary counts, claim counts, and dose counts were added for additional texture.  After reviewing some of these medications, several medications of interest were selected for further analysis.    

**Add Travis’ Top 10 graph here - Figure X:**

##Overview of Analysis:
With the structure of our data, it was possible to map pricing to counties across the U.S., but it was not feasible to do every combination of contract, plan, and dose variation that existed within the formulary.  It was decided to simplify this as much as possible.  We first limited our data to only prices with a 30-day supply option (vs 60 and 90 supply options).  Our team also elected to democratize the MA and PDP plans by counties in which they were available, ensuring that the data represented the greatest number of pricing options available to any particular county.  From there, the median drug price was established for each 30-day supply of the medication across all dosages and delivery methods remaining from our selection for each county.  This median reflects the price across all contracts and plans for a 30-day supply across all doses and delivery mechanisms within all U.S. counties.  We took several approaches to condensing the data into a useful county-level structure and considered and preserved many other statistics related to plan density, contract density, and price spread, to name a few.  Median price was explicitly selected as an alternative to the mean to resist any outlier prices across contracts and plans.


**Add Ellann’s plan graphs here**


