# Results

Our main hypothesis was that there is likely some demographic that is facing more hardship due to medication price inflation in counties with these demographics within the US. Can we use the demographics of a specific county, along with the median medication prices within said county, to develop a model to predict the medication prices? If yes, we could in the short term advise people with specific medical conditions to move to counties with demographics that provide more favorable medication prices and long-term influence the industry to fix such inequities. 

## Population vs Number of Available Medicare Plans

Given the lack of clear patterns for medication prices across the maps, we turned to a deep dive into the demographics. Our first dive was into the population. Do counties with a larger population have more Medicare plan options, and does this competition lead to lower drug prices? A scatter plot of the number of Medicare Plans available vs the population per county is shown below with a linear fit to show a trend line. {@fig-plans-vs-population} 


```{r}
#| label: fig-plans-vs-population
#| fig-cap: "Correlation between the number of Medicare Plan Options and Total Population by US County in 23Q4"
#| warning: false


library(tidyverse)
library(ggplot2)

summary_table = readRDS("data/summary_table_23Q4.rds")

summary_table2 <- summary_table %>%
  filter(!is.na(total_popE))

# Plot population vs
ggplot(summary_table2, aes(x = num_contract_plans, y = total_popE)) +
  geom_point(alpha = 0.6, color = "gray") +
  scale_y_log10(labels = scales::comma) + 
  geom_smooth(method = "lm", color = "black", se = FALSE, linetype = "dashed") +
  
  labs(
    title = "Number of Medicare Plan Options vs Total Population by US County in 23Q4",
    x = "Number of Medicare Plan Options",
    y = "Total Population (log scale)"
  ) +
  theme_minimal(base_size = 10) + 
  theme(
    plot.title.position = "plot",       # aligns title with plot area
    plot.title = element_text(hjust = 0) # hjust = 0 means left-align
  )

```

While there is a slight trend, it is not a great fit overall. The model is statistically significant (p-value < 0.05) and shows a moderate positive relationship (slope = 0.0195, or 1 more medicare plan with a 1.95% increase in the population) between the number of Medicare plans and population. But it's not a strong fit. Two-thirds of the variation in population is left unexplained (adjusted R-squared = 0.3444), so we don’t want to over-interpret this model as being predictive. Given the limited correlation between the number of available plans and population, we don’t think this demographic measure is having much of an impact on medication prices. 
 
From here, we jumped into creating a model across all our demographics (age, education, gender, and racial breakdowns, as well as median income, and percent below the poverty line). 

***ADD MACHINE LEARNING STUFF***

This regional variation underscores the importance of localized analysis. It also raises important questions about equity and access—particularly for beneficiaries in high-cost areas who may face greater financial burdens for the same treatments available at lower costs elsewhere. These disparities suggest that systemic inefficiencies or market imbalances may be at play, warranting further investigation and policy attention.


