project:
 type: manuscript
 output-dir: _output
 resources:
   - "_*.qmd"

manuscript:
 article: capstone.qmd

format:
 html:
   theme:
     light: lightly
     dark: darkly

# execute:
  # freeze: auto
# 
# project:
#   type: website
#   output-dir: _output
# 
# format: 
#   html:
#     toc: true
#     toc-location: left
#     page-layout: full
#     theme:
#       light: lightly
#       dark: darkly
#     mermaid:
#       theme: forest
#     
# with:
#   target: gh-pages
#   path: capstone.qmd
# 
# comments:
#   hypothesis: false