<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.32">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Predicting Medicare Medication Costs Across US Demographics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark-2fef5ea3f8957b3e4ecc936fc74692ca.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-37eea08aefeeee20ff55810ff984fec1.css" rel="stylesheet" class="quarto-color-scheme-extra" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark-b15df86742554840d07b04d0f56a07e9.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<link href="site_libs/bootstrap/bootstrap-81267100e462c21b3d6c0d5bf76a3417.min.css" rel="stylesheet" append-hash="true" class="quarto-color-scheme-extra" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<style>

      .quarto-title-block .quarto-title-banner h1,
      .quarto-title-block .quarto-title-banner h2,
      .quarto-title-block .quarto-title-banner h3,
      .quarto-title-block .quarto-title-banner h4,
      .quarto-title-block .quarto-title-banner h5,
      .quarto-title-block .quarto-title-banner h6
      {
        color: #D8DEE9;
      }

      .quarto-title-block .quarto-title-banner {
        color: #D8DEE9;
background: linear-gradient(45deg, rgb(186, 12, 47) 0%, rgb(0,0,0) 100%);;
      }
</style>


<meta name="citation_title" content="Predicting Medicare Medication Costs Across US Demographics">
<meta name="citation_author" content="Ellann Cohen and Travis McKenzie">
<meta name="citation_language" content="en">
<meta name="citation_reference" content="citation_title=Public opinion on prescription drugs and their prices;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_fulltext_html_url=https://www.kff.org/health-costs/poll-finding/public-opinion-on-prescription-drugs-and-their-prices/;">
<meta name="citation_reference" content="citation_title=2025 scorecard on state health system performance, fragile progress, continuing disparities;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.commonwealthfund.org/publications/scorecard/2025/jun/2025-scorecard-state-health-system-performance;">
<meta name="citation_reference" content="citation_title=CMS data navigator;,citation_author=Centers for Medicare &amp;amp;amp; Medicaid Services;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://data.cms.gov/;">
<meta name="citation_reference" content="citation_title=GoodRx: Prescription drug prices and coupons;,citation_author=GoodRx;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.goodrx.com;">
<meta name="citation_reference" content="citation_title=Tidycensus: Load US census boundary and attribute data as ’tidyverse’ and ’sf’-ready data frames;,citation_author=Kyle Walker;,citation_author=Matt Herman;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://walker-data.com/tidycensus/;">
<meta name="citation_reference" content="citation_title=Data.census.gov: Explore census data;,citation_author=U.S. Census Bureau;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://data.census.gov/;">
<meta name="citation_reference" content="citation_title=National drug code directory;,citation_author=U.S. Food and Drug Administration;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.fda.gov/drugs/drug-approvals-and-databases/national-drug-code-directory;">
<meta name="citation_reference" content="citation_title=Study finds oral semaglutide vastly reduces heart attacks, strokes;,citation_author=UNC Health;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://news.unchealthcare.org/2025/03/study-finds-oral-semaglutide-vastly-reduces-heart-attacks-strokes/;">
<meta name="citation_reference" content="citation_title=Medicare drug price negotiation program: Negotiated prices for initial price applicability year 2026;,citation_author=Centers for Medicare &amp;amp;amp; Medicaid Services;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_fulltext_html_url=https://www.cms.gov/newsroom/fact-sheets/medicare-drug-price-negotiation-program-negotiated-prices-initial-price-applicability-year-2026;">
<meta name="citation_reference" content="citation_title=HHS announces cost savings for 64 prescription drugs thanks to medicare prescription drug inflation rebate;,citation_author=Centers for Medicare &amp;amp;amp; Medicaid Services;,citation_publication_date=2024;,citation_cover_date=2024;,citation_year=2024;,citation_fulltext_html_url=https://www.cms.gov/newsroom/press-releases/hhs-announces-cost-savings-64-prescription-drugs-thanks-medicare-prescription-drug-inflation-rebate;">
<meta name="citation_reference" content="citation_title=Who’s eligible for medicare?;,citation_author=U.S. Department of Health &amp;amp;amp; Human Services;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://www.hhs.gov/answers/medicare-and-medicaid/who-is-eligible-for-medicare/index.html;">
<meta name="citation_reference" content="citation_title=Change to county-equivalents in the state of connecticut;,citation_author=Federal Register: The Daily Journal of the United States Government;,citation_publication_date=2022;,citation_cover_date=2022;,citation_year=2022;,citation_fulltext_html_url=https://www.federalregister.gov/documents/2022/06/06/2022-12063/change-to-county-equivalents-in-the-state-of-connecticut;">
<meta name="citation_reference" content="citation_title=Parts of medicare;,citation_author=Medicare.gov;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.medicare.gov/basics/get-started-with-medicare/medicare-basics/parts-of-medicare;">
<meta name="citation_reference" content="citation_title=How much does medicare drug coverage cost?;,citation_author=Medicare.gov;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.medicare.gov/health-drug-plans/part-d/basics/costs;">
<meta name="citation_reference" content="citation_title=Variation in drug prices at pharmacies: Are prices higher in poorer areas?;,citation_author=Walid F. Gellad;,citation_author=Niteesh K. Choudhry;,citation_author=Mark W. Friedberg;,citation_author=M. Alan Brookhart;,citation_author=Jennifer S. Haas;,citation_author=William H. Shrank;,citation_publication_date=2009;,citation_cover_date=2009;,citation_year=2009;,citation_issue=2 Pt 1;,citation_doi=10.1111/j.1475-6773.2008.00917.x;,citation_volume=44;,citation_journal_title=Health Services Research;">
<meta name="citation_reference" content="citation_title=GAO‑21‑282: &amp;amp;amp;lt;i&amp;gt;Prescription drugs - u.s. Prices for selected brand drugs were higher on average then prices in australia, canada, and france&amp;lt;/i&amp;gt;;,citation_author=U.S. Government Accountability Office;,citation_publication_date=2021;,citation_cover_date=2021;,citation_year=2021;,citation_fulltext_html_url=https://www.gao.gov/products/gao-21-282;,citation_technical_report_institution=U.S. Government Accountability Office;,citation_technical_report_number=GAO‑21‑282;">
<meta name="citation_reference" content="citation_title=Making medicines affordable: A national imperative.;,citation_author=National Academies of Sciences, Engineering, and Medicine; Health and Medicine Division; Board on Health Care Services; Committee on Ensuring Patient Access to Affordable Drug Therapies; ;,citation_editor=Augustine NR Nass SJ;,citation_publication_date=2017;,citation_cover_date=2017;,citation_year=2017;,citation_fulltext_html_url=https://www.ncbi.nlm.nih.gov/books/NBK493090/;,citation_inbook_title=undefined;">
<meta name="citation_reference" content="citation_title=Cost plus drugs: Prescription medications at fair prices;,citation_author=Cost Plus Drugs;,citation_publication_date=2025;,citation_cover_date=2025;,citation_year=2025;,citation_fulltext_html_url=https://www.costplusdrugs.com/;">
</head>

<body class="quarto-light"><script id="quarto-html-before-body" type="application/javascript">
    const toggleBodyColorMode = (bsSheetEl) => {
      const mode = bsSheetEl.getAttribute("data-mode");
      const bodyEl = window.document.querySelector("body");
      if (mode === "dark") {
        bodyEl.classList.add("quarto-dark");
        bodyEl.classList.remove("quarto-light");
      } else {
        bodyEl.classList.add("quarto-light");
        bodyEl.classList.remove("quarto-dark");
      }
    }
    const toggleBodyColorPrimary = () => {
      const bsSheetEl = window.document.querySelector("link#quarto-bootstrap:not([rel=disabled-stylesheet])");
      if (bsSheetEl) {
        toggleBodyColorMode(bsSheetEl);
      }
    }
    const setColorSchemeToggle = (alternate) => {
      const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
      for (let i=0; i < toggles.length; i++) {
        const toggle = toggles[i];
        if (toggle) {
          if (alternate) {
            toggle.classList.add("alternate");
          } else {
            toggle.classList.remove("alternate");
          }
        }
      }
    };
    const toggleColorMode = (alternate) => {
      // Switch the stylesheets
      const primaryStylesheets = window.document.querySelectorAll('link.quarto-color-scheme:not(.quarto-color-alternate)');
      const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
      manageTransitions('#quarto-margin-sidebar .nav-link', false);
      if (alternate) {
        // note: dark is layered on light, we don't disable primary!
        enableStylesheet(alternateStylesheets);
        for (const sheetNode of alternateStylesheets) {
          if (sheetNode.id === "quarto-bootstrap") {
            toggleBodyColorMode(sheetNode);
          }
        }
      } else {
        disableStylesheet(alternateStylesheets);
        enableStylesheet(primaryStylesheets)
        toggleBodyColorPrimary();
      }
      manageTransitions('#quarto-margin-sidebar .nav-link', true);
      // Switch the toggles
      setColorSchemeToggle(alternate)
      // Hack to workaround the fact that safari doesn't
      // properly recolor the scrollbar when toggling (#1455)
      if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
        manageTransitions("body", false);
        window.scrollTo(0, 1);
        setTimeout(() => {
          window.scrollTo(0, 0);
          manageTransitions("body", true);
        }, 40);
      }
    }
    const disableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        stylesheet.rel = 'disabled-stylesheet';
      }
    }
    const enableStylesheet = (stylesheets) => {
      for (let i=0; i < stylesheets.length; i++) {
        const stylesheet = stylesheets[i];
        if(stylesheet.rel !== 'stylesheet') { // for Chrome, which will still FOUC without this check
          stylesheet.rel = 'stylesheet';
        }
      }
    }
    const manageTransitions = (selector, allowTransitions) => {
      const els = window.document.querySelectorAll(selector);
      for (let i=0; i < els.length; i++) {
        const el = els[i];
        if (allowTransitions) {
          el.classList.remove('notransition');
        } else {
          el.classList.add('notransition');
        }
      }
    }
    const isFileUrl = () => {
      return window.location.protocol === 'file:';
    }
    const hasAlternateSentinel = () => {
      let styleSentinel = getColorSchemeSentinel();
      if (styleSentinel !== null) {
        return styleSentinel === "alternate";
      } else {
        return false;
      }
    }
    const setStyleSentinel = (alternate) => {
      const value = alternate ? "alternate" : "default";
      if (!isFileUrl()) {
        window.localStorage.setItem("quarto-color-scheme", value);
      } else {
        localAlternateSentinel = value;
      }
    }
    const getColorSchemeSentinel = () => {
      if (!isFileUrl()) {
        const storageValue = window.localStorage.getItem("quarto-color-scheme");
        return storageValue != null ? storageValue : localAlternateSentinel;
      } else {
        return localAlternateSentinel;
      }
    }
    const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
      const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
      const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
      let newTheme = '';
      if(authorPrefersDark) {
        newTheme = isAlternate ? baseTheme : alternateTheme;
      } else {
        newTheme = isAlternate ? alternateTheme : baseTheme;
      }
      const changeGiscusTheme = () => {
        // From: https://github.com/giscus/giscus/issues/336
        const sendMessage = (message) => {
          const iframe = document.querySelector('iframe.giscus-frame');
          if (!iframe) return;
          iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
        }
        sendMessage({
          setConfig: {
            theme: newTheme
          }
        });
      }
      const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
      if (isGiscussLoaded) {
        changeGiscusTheme();
      }
    };
    const authorPrefersDark = false;
    const darkModeDefault = authorPrefersDark;
      document.querySelector('link#quarto-text-highlighting-styles.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
      document.querySelector('link#quarto-bootstrap.quarto-color-scheme-extra').rel = 'disabled-stylesheet';
    let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
    // Dark / light mode switch
    window.quartoToggleColorScheme = () => {
      // Read the current dark / light value
      let toAlternate = !hasAlternateSentinel();
      toggleColorMode(toAlternate);
      setStyleSentinel(toAlternate);
      toggleGiscusIfUsed(toAlternate, darkModeDefault);
      window.dispatchEvent(new Event('resize'));
    };
    // Switch to dark mode if need be
    if (hasAlternateSentinel()) {
      toggleColorMode(true);
    } else {
      toggleColorMode(false);
    }
  </script>

<header id="title-block-header" class="quarto-title-block default toc-left page-columns page-full">
  <div class="quarto-title-banner page-columns page-full">
    <div class="quarto-title column-body">
      <h1 class="title">Predicting Medicare Medication Costs Across US Demographics</h1>
            <p class="subtitle lead"></p><p>Can demographic information predict medication costs for Medicare patients?</p><p></p>
          </div>

    
    <div class="quarto-title-meta-container">
      <div class="quarto-title-meta-column-start">
        
        <div class="quarto-title-meta">

                <div>
            <div class="quarto-title-meta-heading">Author</div>
            <div class="quarto-title-meta-contents">
                        <p>Ellann Cohen and Travis McKenzie </p>
                      </div>
          </div>
                
          
                
              </div>
      </div>
      <div class="quarto-title-meta-column-end quarto-other-formats-target">
      </div>
    </div>



    <div class="quarto-other-links-text-target">
    </div>  </div>
</header><div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#abstract" id="toc-abstract" class="nav-link active" data-scroll-target="#abstract"><span class="header-section-number">1</span> Abstract</a></li>
  <li><a href="#introduction" id="toc-introduction" class="nav-link" data-scroll-target="#introduction"><span class="header-section-number">2</span> Introduction</a></li>
  <li><a href="#background" id="toc-background" class="nav-link" data-scroll-target="#background"><span class="header-section-number">3</span> Background</a>
  <ul class="collapse">
  <li><a href="#preliminary-research" id="toc-preliminary-research" class="nav-link" data-scroll-target="#preliminary-research"><span class="header-section-number">3.1</span> Preliminary Research</a>
  <ul class="collapse">
  <li><a href="#domestic-impact" id="toc-domestic-impact" class="nav-link" data-scroll-target="#domestic-impact"><span class="header-section-number">3.1.1</span> Domestic Impact</a></li>
  <li><a href="#global-impact" id="toc-global-impact" class="nav-link" data-scroll-target="#global-impact"><span class="header-section-number">3.1.2</span> Global Impact</a></li>
  </ul></li>
  <li><a href="#factors-influencing-medication-affordability" id="toc-factors-influencing-medication-affordability" class="nav-link" data-scroll-target="#factors-influencing-medication-affordability"><span class="header-section-number">3.2</span> Factors Influencing Medication Affordability</a></li>
  <li><a href="#data-landscape" id="toc-data-landscape" class="nav-link" data-scroll-target="#data-landscape"><span class="header-section-number">3.3</span> Data Landscape</a></li>
  <li><a href="#medicare-overview" id="toc-medicare-overview" class="nav-link" data-scroll-target="#medicare-overview"><span class="header-section-number">3.4</span> Medicare Overview</a></li>
  <li><a href="#medicare-part-d-drug-coverage-costs" id="toc-medicare-part-d-drug-coverage-costs" class="nav-link" data-scroll-target="#medicare-part-d-drug-coverage-costs"><span class="header-section-number">3.5</span> Medicare Part D (Drug Coverage) Costs</a></li>
  </ul></li>
  <li><a href="#data" id="toc-data" class="nav-link" data-scroll-target="#data"><span class="header-section-number">4</span> Data</a>
  <ul class="collapse">
  <li><a href="#data-collection" id="toc-data-collection" class="nav-link" data-scroll-target="#data-collection"><span class="header-section-number">4.1</span> Data Collection</a>
  <ul class="collapse">
  <li><a href="#data-sources" id="toc-data-sources" class="nav-link" data-scroll-target="#data-sources"><span class="header-section-number">4.1.1</span> Data Sources</a></li>
  <li><a href="#data-cleaning-and-technical-challenges" id="toc-data-cleaning-and-technical-challenges" class="nav-link" data-scroll-target="#data-cleaning-and-technical-challenges"><span class="header-section-number">4.1.2</span> Data Cleaning and Technical Challenges</a></li>
  </ul></li>
  <li><a href="#data-engineering" id="toc-data-engineering" class="nav-link" data-scroll-target="#data-engineering"><span class="header-section-number">4.2</span> Data Engineering</a></li>
  </ul></li>
  <li><a href="#analysis" id="toc-analysis" class="nav-link" data-scroll-target="#analysis"><span class="header-section-number">5</span> Analysis</a>
  <ul class="collapse">
  <li><a href="#scope-reduction-leveraging-national-spending-data" id="toc-scope-reduction-leveraging-national-spending-data" class="nav-link" data-scroll-target="#scope-reduction-leveraging-national-spending-data"><span class="header-section-number">5.1</span> Scope Reduction Leveraging National Spending Data</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis"><span class="header-section-number">5.2</span> Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#price-variance-across-counties" id="toc-price-variance-across-counties" class="nav-link" data-scroll-target="#price-variance-across-counties"><span class="header-section-number">5.2.1</span> Price Variance Across Counties</a></li>
  <li><a href="#quantity-of-available-medicare-plans" id="toc-quantity-of-available-medicare-plans" class="nav-link" data-scroll-target="#quantity-of-available-medicare-plans"><span class="header-section-number">5.2.2</span> Quantity of Available Medicare Plans</a></li>
  <li><a href="#data-summary-simplifications" id="toc-data-summary-simplifications" class="nav-link" data-scroll-target="#data-summary-simplifications"><span class="header-section-number">5.2.3</span> Data Summary Simplifications</a></li>
  <li><a href="#geographic-medication-price-patterns" id="toc-geographic-medication-price-patterns" class="nav-link" data-scroll-target="#geographic-medication-price-patterns"><span class="header-section-number">5.2.4</span> Geographic Medication Price Patterns</a></li>
  <li><a href="#correlations" id="toc-correlations" class="nav-link" data-scroll-target="#correlations"><span class="header-section-number">5.2.5</span> Correlations</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">6</span> Results</a>
  <ul class="collapse">
  <li><a href="#statistical-testing---phase-1" id="toc-statistical-testing---phase-1" class="nav-link" data-scroll-target="#statistical-testing---phase-1"><span class="header-section-number">6.1</span> Statistical Testing - Phase 1</a>
  <ul class="collapse">
  <li><a href="#hypothesis-1" id="toc-hypothesis-1" class="nav-link" data-scroll-target="#hypothesis-1"><span class="header-section-number">6.1.1</span> Hypothesis 1</a></li>
  <li><a href="#hypothesis-2" id="toc-hypothesis-2" class="nav-link" data-scroll-target="#hypothesis-2"><span class="header-section-number">6.1.2</span> Hypothesis 2</a></li>
  </ul></li>
  <li><a href="#statistical-testing---phase-2" id="toc-statistical-testing---phase-2" class="nav-link" data-scroll-target="#statistical-testing---phase-2"><span class="header-section-number">6.2</span> Statistical Testing - Phase 2</a></li>
  <li><a href="#population-vs-number-of-available-medicare-plans" id="toc-population-vs-number-of-available-medicare-plans" class="nav-link" data-scroll-target="#population-vs-number-of-available-medicare-plans"><span class="header-section-number">6.3</span> Population vs Number of Available Medicare Plans</a></li>
  <li><a href="#machine-learning" id="toc-machine-learning" class="nav-link" data-scroll-target="#machine-learning"><span class="header-section-number">6.4</span> Machine Learning</a>
  <ul class="collapse">
  <li><a href="#model-selection" id="toc-model-selection" class="nav-link" data-scroll-target="#model-selection"><span class="header-section-number">6.4.1</span> Model Selection</a></li>
  <li><a href="#model-performance" id="toc-model-performance" class="nav-link" data-scroll-target="#model-performance"><span class="header-section-number">6.4.2</span> Model Performance</a></li>
  <li><a href="#tuning-to-prevent-overfitting" id="toc-tuning-to-prevent-overfitting" class="nav-link" data-scroll-target="#tuning-to-prevent-overfitting"><span class="header-section-number">6.4.3</span> Tuning to Prevent Overfitting</a></li>
  <li><a href="#feature-importance" id="toc-feature-importance" class="nav-link" data-scroll-target="#feature-importance"><span class="header-section-number">6.4.4</span> Feature Importance</a></li>
  <li><a href="#feature-direction" id="toc-feature-direction" class="nav-link" data-scroll-target="#feature-direction"><span class="header-section-number">6.4.5</span> Feature Direction</a></li>
  <li><a href="#machine-learning-conclusions" id="toc-machine-learning-conclusions" class="nav-link" data-scroll-target="#machine-learning-conclusions"><span class="header-section-number">6.4.6</span> Machine Learning Conclusions</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#conclusions" id="toc-conclusions" class="nav-link" data-scroll-target="#conclusions"><span class="header-section-number">7</span> Conclusions</a>
  <ul class="collapse">
  <li><a href="#insights-and-recommendations" id="toc-insights-and-recommendations" class="nav-link" data-scroll-target="#insights-and-recommendations"><span class="header-section-number">7.1</span> Insights and Recommendations</a></li>
  <li><a href="#ethical-considerations" id="toc-ethical-considerations" class="nav-link" data-scroll-target="#ethical-considerations"><span class="header-section-number">7.2</span> Ethical Considerations</a>
  <ul class="collapse">
  <li><a href="#equity-and-fairness" id="toc-equity-and-fairness" class="nav-link" data-scroll-target="#equity-and-fairness"><span class="header-section-number">7.2.1</span> Equity and Fairness</a></li>
  <li><a href="#purpose-and-impact" id="toc-purpose-and-impact" class="nav-link" data-scroll-target="#purpose-and-impact"><span class="header-section-number">7.2.2</span> Purpose and Impact</a></li>
  <li><a href="#privacy" id="toc-privacy" class="nav-link" data-scroll-target="#privacy"><span class="header-section-number">7.2.3</span> Privacy</a></li>
  </ul></li>
  <li><a href="#future-research" id="toc-future-research" class="nav-link" data-scroll-target="#future-research"><span class="header-section-number">7.3</span> Future Research</a>
  <ul class="collapse">
  <li><a href="#longitudinal-analysis" id="toc-longitudinal-analysis" class="nav-link" data-scroll-target="#longitudinal-analysis"><span class="header-section-number">7.3.1</span> Longitudinal Analysis</a></li>
  <li><a href="#expanded-demographic-analysis" id="toc-expanded-demographic-analysis" class="nav-link" data-scroll-target="#expanded-demographic-analysis"><span class="header-section-number">7.3.2</span> Expanded Demographic Analysis</a></li>
  <li><a href="#geographic-and-environmental-context" id="toc-geographic-and-environmental-context" class="nav-link" data-scroll-target="#geographic-and-environmental-context"><span class="header-section-number">7.3.3</span> Geographic and Environmental Context</a></li>
  <li><a href="#sociopolitical-context" id="toc-sociopolitical-context" class="nav-link" data-scroll-target="#sociopolitical-context"><span class="header-section-number">7.3.4</span> Sociopolitical Context</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8</span> References</a></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content quarto-banner-title-block" id="quarto-document-content">




  


<section id="abstract" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Abstract</h1>
<p>Escalating pharmaceutical prices in the United States present a significant barrier to healthcare access and exacerbate financial strain on patients. This study investigates geographic and demographic disparities in prescription drug costs by analyzing Medicare Part D plan pricing at the county level. To manage and analyze over 100 GB of complex data, we developed a scalable data engineering pipeline utilizing AWS S3, DuckDB, and the Parquet file format. The pipeline integrates datasets from the Centers for Medicare &amp; Medicaid Services (CMS), the U.S. Census Bureau, and the Food and Drug Administration (FDA). We applied statistical analysis and machine learning techniques to examine how demographic and market factors influence drug pricing. Our findings reveal that the number of available Medicare plans in a county is the most influential predictor of price for the majority of drugs studied, underscoring the impact of market dynamics over direct demographic characteristics. While certain demographic variables, such as median income, education level, and racial composition, showed predictive relevance for specific medications, no single demographic factor consistently explained price variation across all drugs. Although our analysis does not conclusively demonstrate disproportionate pricing impacts on any one demographic group, it highlights a complex and inequitable pricing landscape. These insights challenge the efficacy of current Medicare price negotiation mechanisms and suggest that federal and state policymakers should pursue price normalization strategies. Ensuring that the lowest negotiated drug prices are broadly accessible could enhance transparency and affordability for all Medicare beneficiaries.</p>
</section>
<section id="introduction" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Introduction</h1>
<p>Escalating pharmaceutical prices in the U.S. are reshaping public health policy, widening healthcare disparities, and straining the financial well-being of millions. A recent KFF poll found that 60% of adults take at least one prescription, and 25% take four or more <span class="citation" data-cites="KFF2024">(<a href="#ref-KFF2024" role="doc-biblioref"><span>“Public Opinion on Prescription Drugs and Their Prices”</span> 2024</a>)</span>. Yet, as pharmaceutical technology advances, affordability remains a significant concern. Even with coverage through Medicare, Medicaid, or private insurance, many patients face high out-of-pocket costs that contribute to financial stress and, in some cases, treatment avoidance.</p>
<p>According to the Commonwealth Fund <span class="citation" data-cites="TCF2025">(<a href="#ref-TCF2025" role="doc-biblioref"><span>“2025 Scorecard on State Health System Performance, Fragile Progress, Continuing Disparities”</span> 2025</a>)</span>, 30% of U.S. adults carry medical debt, and nearly 57% of under-insured adults delay or avoid necessary treatment due to cost. This financial strain is compounded by the fragmented structure of public insurance programs like Medicare and Medicaid, which serve only specific populations and vary widely by state and county. These regional differences in plan availability and coverage often translate into significant disparities in pricing and out-of-pocket costs, further undermining equitable access to care.</p>
<p>While medications are only one aspect of medical care, they are essential in preventing more costly interventions. Chronic conditions such as diabetes, cardiovascular disease, and kidney disease can often be effectively managed with medication, reducing the need for hospitalization or surgery. A recent study by UNC Health <span class="citation" data-cites="unc2025semaglutide">(<a href="#ref-unc2025semaglutide" role="doc-biblioref">UNC Health 2025</a>)</span> found that oral semaglutide (marketed as Ozempic and Rybelsus for diabetes, and Wegovy for weight loss) significantly lowered the risk of heart attacks and strokes. This underscores that medication affordability is not merely a matter of convenience but a foundation of equitable, cost-effective healthcare.</p>
<p>This project examines the costs associated with Medicare prescription drug plans and their impact on different demographic groups across the U.S. By analyzing how plan pricing varies by state and county, we aim to better understand the financial burden on under-served populations. The findings will highlight geographic and socioeconomic disparities in medication affordability and may inform policy changes, or targeted interventions to advance health equity.</p>
<p>To support this analysis, we integrated publicly available data from the Centers for Medicare &amp; Medicaid Services (CMS), the U.S. Census Bureau, and the Food and Drug Administration (FDA). These datasets provide detailed information on drug pricing, clinical use, demographic characteristics, and public insurance coverage specifically for Medicare patients. We brought together all datasets into a single DuckDB database on AWS S3, allowing for efficient and scalable data queries. This setup supports a thorough investigation of drug spending patterns and helps model costs based on demographic factors.</p>
</section>
<section id="background" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Background</h1>
<section id="preliminary-research" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="preliminary-research"><span class="header-section-number">3.1</span> Preliminary Research</h2>
<section id="domestic-impact" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="domestic-impact"><span class="header-section-number">3.1.1</span> Domestic Impact</h3>
<p>In the United States, a 2009 study titled “Variation in Drug Prices at Pharmacies: Are Prices Higher in Poorer Areas?” <span class="citation" data-cites="gellad2009variation">(<a href="#ref-gellad2009variation" role="doc-biblioref">Gellad et al. 2009</a>)</span> examined mean retail prices for four commonly prescribed medications across Florida. The researchers compared these prices to median ZIP code income data from the 2000 census. Their findings revealed that, on average, drug prices in the poorest ZIP codes were 9% higher than the statewide average, suggesting a troubling correlation between socioeconomic status and pharmaceutical costs.</p>
</section>
<section id="global-impact" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="global-impact"><span class="header-section-number">3.1.2</span> Global Impact</h3>
<p>Internationally, disparities in drug pricing persist. A 2021 report from the U.S. Government Accountability Office <span class="citation" data-cites="gao2021_21_282">(<a href="#ref-gao2021_21_282" role="doc-biblioref">U.S. Government Accountability Office 2021</a>)</span> found that prices for selected brand-name drugs in the United States were, on average, higher than those in Australia, Canada, and France. While some medications were priced only slightly above international benchmarks, others cost up to ten times more than their counterparts abroad, underscoring the extent of pricing variability and the relative inefficiency of the U.S. pharmaceutical market.</p>
</section>
</section>
<section id="factors-influencing-medication-affordability" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="factors-influencing-medication-affordability"><span class="header-section-number">3.2</span> Factors Influencing Medication Affordability</h2>
<p>According to the National Academies of Sciences, Engineering, and Medicine <span class="citation" data-cites="ncbi_nbk493090">(<a href="#ref-ncbi_nbk493090" role="doc-biblioref">National Academies of Sciences, Engineering, and Medicine; Health and Medicine Division; Board on Health Care Services; Committee on Ensuring Patient Access to Affordable Drug Therapies; 2017</a>)</span>, many factors affect medication affordability. The factors that seem most important for our investigation are “the interaction of market power, health insurance, and the lack of effective incentives for controlling product price”, “unequal bargaining power between buyers and sellers”, “insurance benefit designs with significant patient cost-sharing provisions”, and “inadequate performance of patient assistance programs and other public programs intended to make medicines more affordable for patients.”</p>
<p>For consumers, few levers exist to lower costs. One option is choosing where to purchase medications, though this assumes access to multiple pharmacies and the ability to travel. The other is selecting a health insurance plan, but the availability of plan options varies widely by region. In many cases, geographic location, something individuals often cannot control, significantly limits affordable choices.</p>
</section>
<section id="data-landscape" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="data-landscape"><span class="header-section-number">3.3</span> Data Landscape</h2>
<p>Medication prices vary depending on one’s insurance plan, the pharmacy, the dosage of medication, generic or name-brand, and more. When looking for medication prices for our analysis, we initially explored several APIs from online pharmacies, including GoodRx <span class="citation" data-cites="goodrx2025">(<a href="#ref-goodrx2025" role="doc-biblioref">GoodRx 2025</a>)</span> and CostPlusDrugs <span class="citation" data-cites="costplusdrugs2025">(<a href="#ref-costplusdrugs2025" role="doc-biblioref">Cost Plus Drugs 2025</a>)</span>, which aim to improve consumer price transparency. However, these sources could not be reliably linked to the county-level demographic data essential to our analysis.</p>
<p>Consequently, we turned to the Centers for Medicare &amp; Medicaid Services (CMS), which offers several of the most comprehensive public datasets on healthcare coverage and drug pricing. CMS maintains over 100 datasets spanning prescription costs, plan structures, and beneficiary demographics <span class="citation" data-cites="cms2025data">(<a href="#ref-cms2025data" role="doc-biblioref">Centers for Medicare &amp; Medicaid Services 2025</a>)</span>. One Medicare-based dataset, in particular, allowed for medication pricing to be tied to geographic location, which could then be paired with demographic data. While the dataset is limited to Medicare beneficiaries, it still serves as a strong proxy for broader drug pricing trends. Medicare Part D covers over 50 million people and negotiates prices through private insurers, making it a major market influencer. Its pricing often anchors costs across the healthcare system, suggesting that other buyers likely pay similar or higher prices.</p>
<p>For demographic data, the most obvious choice was to use the demographic data collected every 10 years by the US Census <span class="citation" data-cites="uscensus2025">(<a href="#ref-uscensus2025" role="doc-biblioref">U.S. Census Bureau 2025</a>)</span>.</p>
</section>
<section id="medicare-overview" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="medicare-overview"><span class="header-section-number">3.4</span> Medicare Overview</h2>
<p>Medicare eligibility typically begins at age 65, though individuals with disabilities, end-stage renal disease (ESRD), or ALS may qualify earlier <span class="citation" data-cites="medicareEligibility">(<a href="#ref-medicareEligibility" role="doc-biblioref">U.S. Department of Health &amp; Human Services 2022</a>)</span>. Enrollment must occur within three months before or after one’s 65th birthday to avoid late penalties.</p>
<p>Medicare consists of four main parts <span class="citation" data-cites="medicareParts">(<a href="#ref-medicareParts" role="doc-biblioref">Medicare.gov 2025b</a>)</span>:</p>
<ul>
<li>Part A – Hospital insurance (inpatient care, skilled nursing, hospice, home health)</li>
<li>Part B – Medical insurance (doctor visits, outpatient care, equipment, preventive services)</li>
<li>Part D – Prescription drug coverage</li>
<li>Medigap – Supplemental insurance (available only with Original Medicare)</li>
</ul>
<p>Coverage can be obtained through:</p>
<ul>
<li>Original Medicare – Includes Parts A and B; Part D and Medigap must be purchased separately.</li>
<li>Medicare Advantage (Part C) – Bundles Parts A, B, and often D, offered by private insurers.</li>
</ul>
</section>
<section id="medicare-part-d-drug-coverage-costs" class="level2" data-number="3.5">
<h2 data-number="3.5" class="anchored" data-anchor-id="medicare-part-d-drug-coverage-costs"><span class="header-section-number">3.5</span> Medicare Part D (Drug Coverage) Costs</h2>
<p>Medicare Part D costs vary by plan and may include a monthly premium, an annual deductible (up to $590 in 2025), copayments (fixed amounts), and coinsurance (percentage-based costs) <span class="citation" data-cites="medicarePartDCosts">(<a href="#ref-medicarePartDCosts" role="doc-biblioref">Medicare.gov 2025a</a>)</span>. Prices for the same medication and dosage can differ across pharmacies and even within the same pharmacy depending on the selected plan. Not all plans cover all medications, adding another layer of complexity. Given that most 65-year-olds take multiple prescriptions, choosing the most cost-effective plan and pharmacy can be overwhelming, making Medicare enrollment confusing.</p>
</section>
</section>
<section id="data" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Data</h1>
<section id="data-collection" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="data-collection"><span class="header-section-number">4.1</span> Data Collection</h2>
<section id="data-sources" class="level3" data-number="4.1.1">
<h3 data-number="4.1.1" class="anchored" data-anchor-id="data-sources"><span class="header-section-number">4.1.1</span> Data Sources</h3>
<p>We selected the CMS Quarterly Prescription Drug Plan Formulary as our primary data source, utilizing pricing, formulary, plan information, and geographic locator files to map drug prices and plan availability at the county level. The formulary offered a rare combination of granularity, geographic coverage, and accessibility, making it a practical foundation for our analysis.</p>
<p>Demographic data selection was straightforward. U.S. Census county-level data was collected using the Tidycensus <span class="citation" data-cites="tidycensus2025">(<a href="#ref-tidycensus2025" role="doc-biblioref">Walker and Herman 2025</a>)</span> package in R. Key variables included age, education, gender, race, total population, median income, and poverty rates.</p>
<p>To interpret drug references in the CMS datasets, which list medications by National Drug Code (NDC) only, we added the FDA’s NDC Directory <span class="citation" data-cites="fda2025ndc">(<a href="#ref-fda2025ndc" role="doc-biblioref">U.S. Food and Drug Administration 2025</a>)</span> to match codes with drug names.</p>
<p>In addition to the formulary, we integrated three national-level CMS datasets (Medicare Part B, Part D, and Medicaid, 2019–2023) to contextualize drug spending trends. Although lacking county-level detail, these datasets highlighted medications with the highest national financial impact.</p>
</section>
<section id="data-cleaning-and-technical-challenges" class="level3" data-number="4.1.2">
<h3 data-number="4.1.2" class="anchored" data-anchor-id="data-cleaning-and-technical-challenges"><span class="header-section-number">4.1.2</span> Data Cleaning and Technical Challenges</h3>
<p>Although the previous section may suggest that combining and storing the data was straightforward, the data cleaning and processing phase presented a significant challenge, consistent with the complexities typical of most data science projects.</p>
<p>The CMS Quarterly Prescription Drug Plan Formulary datasets were significantly larger than those our team had previously worked with. Each quarterly file from 2019 Q1 through 2025 Q1 contained approximately 10–12 GB of compressed data. To manage scope, we narrowed our focus to the 2023 Q4 dataset. Even within this single quarter, the formulary included pricing data for approximately 6,336 unique medications (identified by NDC codes), across multiple dosage strengths and 30-, 60-, and 90-day supply options. These were distributed across 5,644 unique contract/plan combinations. Some Medicare plan options were listed at the county level, while others were available only at the broader regional level, either as Medicare Advantage (MA, also known as Part C) or Prescription Drug Plans (PDP). To align these regional plans with our census-based demographic data, we disaggregated them by county. Medication prices varied not only by NDC code, but also by supply duration, dosage strength (e.g., 10 mg, 30 mg, 50 mg daily), delivery mechanism (e.g., pill, patch, injection, liquid), and Medicare plan.</p>
<p>A key limitation of the CMS formulary data was the absence of drug names, listing only 11-digit National Drug Code (NDC) identifiers. Meanwhile, the overall spending datasets included drug names but lacked NDCs, preventing direct linkage. Since NDCs are not easily interpretable, converting them to readable names was essential for analysis.</p>
<p>To bridge this gap, we used the FDA’s National Drug Code Directory <span class="citation" data-cites="fda2025ndc">(<a href="#ref-fda2025ndc" role="doc-biblioref">U.S. Food and Drug Administration 2025</a>)</span>, which provides detailed drug identification. However, formatting inconsistencies, such as missing leading zeros and compressed segments, required standardizing both datasets to a 9-digit format by removing package-level detail and adjusting segment lengths.</p>
<p>After extensive cleaning, we successfully matched FDA drug names to CMS formulary entries. Fortunately, naming conventions in the spending data aligned closely with FDA standards (95% match), enabling us to relate national spending figures to county-level prices and plan availability. This integration created a robust, interconnected database across multiple large-scale datasets.</p>
<p>During the geographic analysis, we identified a unique complication related to Connecticut. In 2022, all Connecticut counties were renamed and had their boundaries redrawn <span class="citation" data-cites="countiesConnecticut">(<a href="#ref-countiesConnecticut" role="doc-biblioref">Federal Register: The Daily Journal of the United States Government 2022</a>)</span>. While our primary focus was on Q4 2023 data, a discrepancy emerged: CMS data continued to use the pre-2022 county names and boundaries, whereas the U.S. Census Bureau adopted the updated designations. Because the county shapes also changed, we applied engineering judgment to map the old county definitions to the new ones. As a result, any county-level analysis for Connecticut should be interpreted as an approximation. Data for all other U.S. counties remains accurate once spellings were matched.</p>
</section>
</section>
<section id="data-engineering" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="data-engineering"><span class="header-section-number">4.2</span> Data Engineering</h2>
<p>The project faced substantial challenges in gathering and assembling the data, chief among them, the scale and accessibility of the files. The volume of data, which exceeded 100 GB compressed (nearly 300 GB uncompressed), far surpassed the file size limitations imposed by GitHub. While GitHub does offer a Large File Storage (LFS) extension, it was not sufficient for the scope of this project. Moreover, the team needed a collaborative environment where all members could access, modify, and validate shared datasets without working in silos, which could risk data inconsistency.</p>
<p>To address this, and upon the recommendation of Professor Jed Rembold, we explored several cloud storage options. After evaluating the alternatives, Amazon Web Services (AWS) S3 (Simple Storage Service) was selected for its flexibility, scalability, and broad support within the data science community. Using an S3 bucket, we created a centralized, cloud-based storage system that allowed team members to upload, retrieve, and organize large datasets seamlessly.</p>
<p>Implementing this solution was not trivial. Neither team member had prior experience with AWS, and the learning curve was significant. Support from large language models (LLMs) such as the AWS integrated LLM assistant, Microsoft Copilot, GitHub Copilot and ChatGPT proved instrumental in navigating technical setup, access permissions, and authentication. The result was a robust, scalable storage infrastructure that underpinned our data pipeline and enabled consistent access and collaboration throughout the project.</p>
<p>Setting up the AWS S3 bucket was only the first step in implementing a robust data infrastructure. Professor Rembold also recommended using DuckDB, an in-process SQL OLAP (Online Analytical Processing) database designed for high-performance analytical queries on large datasets. Unlike traditional database systems, DuckDB operates without a dedicated server, making it ideal for decentralized, collaborative data science workflows.</p>
<p>A third critical recommendation was to convert all raw data, originally provided in CSV and text formats by CMS, the FDA, and the U.S. Census Bureau, into Parquet. Parquet is a columnar storage format optimized for analytical workloads. Parquet offers efficient compression and schema evolution, and it integrates seamlessly with DuckDB. By adopting Parquet, we reduced storage costs and improved query speed, allowing us to manage and process the dataset more effectively within the AWS S3 environment.</p>
<p>Together, AWS S3, DuckDB, and Parquet formed a cohesive, scalable solution. The team was able to interface with this infrastructure using R, enabling the creation of reusable scripts that could be stored and version-controlled in GitHub. This structure supported asynchronous collaboration, ensured data consistency, and also allowed us to explore advanced features of RStudio, particularly its GitHub integration.</p>
<p>Over 100 Parquet files were ultimately stored in the AWS S3 bucket, many representing variations of plan files, geographic locator files, drug formulary files, and pricing data from the CMS Quarterly Prescription Drug Plan Formulary dataset. While not all files were used in the final analysis, early-stage exploration required access to every quarter from 2019 to 2023. In contrast, the U.S. Census, FDA NDC, and CMS spending datasets were far smaller and could have been managed locally. However, the CMS formulary data’s size and complexity made scalable storage essential. Though it introduced some engineering challenges, using S3 was ultimately the right choice. It enabled the creation of a structured, relational database across a large, disparate dataset.</p>
<p>We implemented an ELT (Extract, Load, Transform) pipeline, extracting data from source systems and loading it into an AWS S3 bucket as a centralized warehouse. Transformations and analysis were performed using R scripts and DuckDB’s SQL interface on Parquet files. Version control via GitHub enabled collaborative, reproducible workflows and scalable, iterative analysis.</p>
<p>Standardizing NDC formats across CMS and FDA datasets allowed consistent linkage of drug identifiers, enabling reliable mapping between county-level pricing, national spending data, and drug names. By the end of the data engineering phase, we had built a fully connected architecture that linked U.S. Census demographics to Medicare Part D pricing, mapped those prices to NDC codes, and connected them to national drug spending. This relational framework supported robust geographic and demographic analysis of medication costs across the U.S.</p>
</section>
</section>
<section id="analysis" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Analysis</h1>
<section id="scope-reduction-leveraging-national-spending-data" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="scope-reduction-leveraging-national-spending-data"><span class="header-section-number">5.1</span> Scope Reduction Leveraging National Spending Data</h2>
<p>One of the first goals was to understand the connected data at a high level by condensing and aggregating details. Due to the granularity of the formulary data, it was necessary to narrow the focus rather than analyze all 6,000+ medications. The CMS spending datasets provided a clearer, structured view and helped identify high-impact drugs. Using this data, we generated top drug lists by total spend, claims, and doses (<a href="#fig-topspend" class="quarto-xref">Figure&nbsp;1</a>), ultimately selecting a few key medications for deeper analysis. Initially, we reviewed the top 10 and top 25 by total spending.</p>
<div id="cell-fig-topspend" class="cell">
<div class="cell-output-display">
<div id="fig-topspend" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-topspend-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-topspend-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;1: Top Medication Spending from 2019 - 2022 across Medicare Part B, D and Medicaid"><img src="capstone_files/figure-html/fig-topspend-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-topspend-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Top Medication Spending from 2019 - 2022 across Medicare Part B, D and Medicaid
</figcaption>
</figure>
</div>
</div>
</div>
<p>We were not able to match all the top drugs to our dataset, so we used only the ones that had full matches, which ended up being the 14 of the top 25 medications. To help contextualize what conditions these medications treat, see <a href="#tbl-topmeds" class="quarto-xref">Table&nbsp;1</a> below.</p>
<div style="font-size: 90%;">
<div id="tbl-topmeds" class="striped hover quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[20,20,20,40]">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-topmeds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover table">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 40%">
</colgroup>
<thead>
<tr class="header">
<th>Total Spend (USD)</th>
<th>Generic Name</th>
<th>Brand Name(s)</th>
<th>Common Treatment Conditions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>$67.3B</td>
<td>Apixaban</td>
<td>Eliquis</td>
<td>AFib (Atrial Fibrillation), DVT/PE (Deep Vein Thrombosis / Pulmonary Embolism), Post-surgery Prophylaxis</td>
</tr>
<tr class="even">
<td>$43.1B</td>
<td>Adalimumab</td>
<td>Humira, Biosimilars</td>
<td>chronic inflammatory or autoimmune conditions such as RA (Rheumatoid Arthritis), PsA (Psoriatic Arthritis), AS (Ankylosing Spondylitis), CD (Crohn’s Disease), UC (Ulcerative Colitis), Psoriasis, JIA (Juvenile Idiopathic Arthritis), uveitis</td>
</tr>
<tr class="odd">
<td>$30.9B</td>
<td>Dulaglutide</td>
<td>Trulicity</td>
<td>Type 2 Diabetes</td>
</tr>
<tr class="even">
<td>$29.9B</td>
<td>Lenalidomide</td>
<td>Revlimid</td>
<td>Multiple Myeloma, MDS (Myelodysplastic Syndromes)</td>
</tr>
<tr class="odd">
<td>$28.4B</td>
<td>Rivaroxaban</td>
<td>Xarelto</td>
<td>AFib (Atrial Fibrillation), DVT/PE (Deep Vein Thrombosis / Pulmonary Embolism)</td>
</tr>
<tr class="even">
<td>$26.9B</td>
<td>Empagliflozin</td>
<td>Jardiance</td>
<td>Type 2 Diabetes, CV risk</td>
</tr>
<tr class="odd">
<td>$26.7B</td>
<td>Semaglutide</td>
<td>Ozempic, Wegovy</td>
<td>Type 2 diabetes, Obesity</td>
</tr>
<tr class="even">
<td>$18.4B</td>
<td>Paliperidone Palmitate</td>
<td>Invega Sustenna/Trinza</td>
<td>Schizophrenia</td>
</tr>
<tr class="odd">
<td>$16.7B</td>
<td>Etanercept</td>
<td>Enbrel</td>
<td>RA (Rheumatoid Arthritis), PsA (Psoriatic Arthritis), AS (Ankylosing Spondylitis), Psoriasis</td>
</tr>
<tr class="even">
<td>$15.7B</td>
<td>Insulin Aspart</td>
<td>Novolog, Fiasp</td>
<td>Type 1 &amp; 2 Diabetes</td>
</tr>
<tr class="odd">
<td>$15.2B</td>
<td>Ustekinumab</td>
<td>Stelara</td>
<td>Psoriasis, PsA (Psoriatic Arthritis), Crohns</td>
</tr>
<tr class="even">
<td>$14.5B</td>
<td>Ibrutinib</td>
<td>Imbruvica</td>
<td>blood cancers such as CLL (Chronic Lymphocytic Leukemia), MCL (Mantle Cell Lymphoma), and WM (Waldenström’s Macroglobulinemia)</td>
</tr>
<tr class="odd">
<td>$12.1B</td>
<td>Tiotropium Bromide</td>
<td>Spiriva</td>
<td>COPD (Chronic Obstructive Pulmonary Disease), Asthma (adjunct)</td>
</tr>
<tr class="even">
<td>$11.6B</td>
<td>Liraglutide</td>
<td>Victoza, Saxenda</td>
<td>Type 2 Diabetes, Obesity</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-topmeds-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Top medications by absolute spend and the treatment conditions
</figcaption>
</figure>
</div>
</div>
</section>
<section id="exploratory-data-analysis" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="exploratory-data-analysis"><span class="header-section-number">5.2</span> Exploratory Data Analysis</h2>
<section id="price-variance-across-counties" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="price-variance-across-counties"><span class="header-section-number">5.2.1</span> Price Variance Across Counties</h3>
<p>After mapping individual medication prices to U.S. counties by which Medicare plans were available, we found far more variability in pricing than expected. Some drugs had over 6,000 unique prices nationwide, with many others exceeding 4,000. A box plot of the top-spending medications is shown below, ordered from highest to lowest total national expenditure (<a href="#fig-pricevariance" class="quarto-xref">Figure&nbsp;2</a>). This visualization highlights the wide variance in drug pricing. Notably, the absolute cost of a medication does not necessarily align with its total national spending. For example, Apixaban, the drug with the highest overall spend, costs only about $10 for a 30-day supply, while another top-spending drug is priced at approximately $26,000 for the same duration.</p>
<div id="cell-fig-pricevariance" class="cell">
<div class="cell-output-display">
<div id="fig-pricevariance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-pricevariance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-pricevariance-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;2: Median price variance in price for top drugs (descending by absolute spending) across the U.S."><img src="capstone_files/figure-html/fig-pricevariance-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-pricevariance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Median price variance in price for top drugs (descending by absolute spending) across the U.S.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="quantity-of-available-medicare-plans" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="quantity-of-available-medicare-plans"><span class="header-section-number">5.2.2</span> Quantity of Available Medicare Plans</h3>
<p>One contributing factor to the wide range of drug prices is the number of Medicare plans available within a given county. Not all prices shown in the previous figure are accessible to every Medicare patient, as plan availability varies by location. To further illustrate this variability at the county level, the bar chart below displays the number of Medicare plans available in each county within a sample state (<a href="#fig-ORplans" class="quarto-xref">Figure&nbsp;3</a>).</p>
<div id="cell-fig-ORplans" class="cell">
<div class="cell-output-display">
<div id="fig-ORplans" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-ORplans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-ORplans-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;3: Quantity of Unique Medicare Plan Counts by Oregon County"><img src="capstone_files/figure-html/fig-ORplans-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-ORplans-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Quantity of Unique Medicare Plan Counts by Oregon County
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="data-summary-simplifications" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="data-summary-simplifications"><span class="header-section-number">5.2.3</span> Data Summary Simplifications</h3>
<p>Given the number of plans within each county (and the variation in drug prices by plan, pharmacy, dosage, and delivery mechanism), we chose to simplify the data by calculating the median 30-day supply price for each drug (based on the 9-digit NDC code) within each county. While 60-day and 90-day supply prices were also available, they were excluded to streamline the analysis. For much of the subsequent work, this median county-level price per drug will serve as our primary target variable.</p>
</section>
<section id="geographic-medication-price-patterns" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="geographic-medication-price-patterns"><span class="header-section-number">5.2.4</span> Geographic Medication Price Patterns</h3>
<p>Our ultimate goal is to use demographic data (tied to geographic location) to predict drug prices in order to figure out which demographic factors have the largest impact on medication prices. Before jumping into the demographic data, we looked at the geographic data.</p>
<p>An early concern in the development of this project was whether there would even be any price variation based on location. A common misconception is that Medicare drug prices are the same across the US, given that Medicare is a public national medical insurance. The results were surprising. Drug prices do vary significantly regionally, sometimes at the state level and sometimes at the county level. A quick scan over many of the drugs shows the lack of geographic patterns for many of the drugs. (See <a href="#fig-map-facet" class="quarto-xref">Figure&nbsp;4</a>). The maps show the median price for a 30-day supply of each drug by county. The color scale is different for each drug, with the highest value for each drug shown in yellow and the lowest in purple.</p>
<div id="cell-fig-map-facet" class="cell">
<div class="cell-output-display">
<div id="fig-map-facet" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-map-facet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-map-facet-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-4" title="Figure&nbsp;4: 30-day supply median drug prices by US County for 14 high total expenditure drugs. Note: The color scale is different for every drug. The highest value for each drug is yellow while the lowest value is purple."><img src="capstone_files/figure-html/fig-map-facet-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-map-facet-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: 30-day supply median drug prices by US County for 14 high total expenditure drugs. Note: The color scale is different for every drug. The highest value for each drug is yellow while the lowest value is purple.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Taking a closer look at two drugs, Semaglutide is one drug that stands out at the state level, as shown in <a href="#fig-map-semaglutide" class="quarto-xref">Figure&nbsp;5</a>. New York state has the lowest median 30-day supply price compared to every other state in the country.</p>
<div id="cell-fig-map-semaglutide" class="cell">
<div class="cell-output-display">
<div id="fig-map-semaglutide" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-map-semaglutide-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-map-semaglutide-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-5" title="Figure&nbsp;5: Median Medicare Price for 30-day Supply of Semaglutide by US County"><img src="capstone_files/figure-html/fig-map-semaglutide-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-map-semaglutide-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Median Medicare Price for 30-day Supply of Semaglutide by US County
</figcaption>
</figure>
</div>
</div>
</div>
<p>Liraglutide is another that stands out in that it has a clear state-wide price impact, like in New Mexico and Minnesota, but a county-level price delta in some counties scattered across other states such as Nebraska, Oregon, Washington, Tennessee, Missouri, and Virginia. (<a href="#fig-map-liraglutide" class="quarto-xref">Figure&nbsp;6</a>)</p>
<div id="cell-fig-map-liraglutide" class="cell">
<div class="cell-output-display">
<div id="fig-map-liraglutide" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-map-liraglutide-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-map-liraglutide-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-6" title="Figure&nbsp;6: Median Medicare Price for 30-day Supply of Liraglutide by US County"><img src="capstone_files/figure-html/fig-map-liraglutide-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-map-liraglutide-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Median Medicare Price for 30-day Supply of Liraglutide by US County
</figcaption>
</figure>
</div>
</div>
</div>
<p>Our team was surprised by what we observed once the median prices were applied to map plots. There are patterns here, but they vary geographically, and the pattern is not the same for different drugs. To see large maps for all of the top drugs, go to this <a href="https://gpc1.shinyapps.io/shiny_maps_drug_median_price/">shiny app</a>.</p>
</section>
<section id="correlations" class="level3" data-number="5.2.5">
<h3 data-number="5.2.5" class="anchored" data-anchor-id="correlations"><span class="header-section-number">5.2.5</span> Correlations</h3>
<p>The age, education, racial, and gender data from the Census are provided as absolute values. We normalized those by dividing each metric by the total population to convert them to percentages. We then explored which demographic metrics most closely correlate to the prices for each medication in <a href="#fig-by-drug-correlation" class="quarto-xref">Figure&nbsp;7</a>. If all the medications are correlated with similar demographic metrics, all drugs can be modeled together. If not, the individual drugs will need to be modeled separately. In this case, we filtered out weak correlations, keeping only those with Pearson correlation coefficients less than -0.1 or greater than 0.1. There is no clear pattern among all the top drugs for correlations with the demographic metrics. Thus, we concluded that each medication needs to be analyzed independently.</p>
<div id="cell-fig-by-drug-correlation" class="cell">
<div class="cell-output-display">
<div id="fig-by-drug-correlation" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-by-drug-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-by-drug-correlation-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-7" title="Figure&nbsp;7: Heatmap of Pearson Correlations Between Demographics and Drug Prices where |Pearson Correlation| > 0.1"><img src="capstone_files/figure-html/fig-by-drug-correlation-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-by-drug-correlation-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;7: Heatmap of Pearson Correlations Between Demographics and Drug Prices where |Pearson Correlation| &gt; 0.1
</figcaption>
</figure>
</div>
</div>
</div>
<p>We also introduced a feature called “Affordability” which divided price by income. This metric showed minimal correlation with other demographic variables also. Even the strongest positive and negative correlations had Pearson coefficients below 0.04, indicating negligible relationships. It failed to yield meaningful insights within our analysis and results.</p>
</section>
</section>
</section>
<section id="results" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Results</h1>
<p>Our primary hypothesis was that certain demographic groups may experience greater hardship due to rising medication prices, particularly in counties where these demographics are concentrated. We asked whether it’s possible to use county-level demographic data, along with median medication prices, to build a predictive model for drug costs. If successful, such a model could offer short-term guidance, helping individuals with specific medical needs identify counties with more favorable pricing, and long-term potential to inform policy and industry efforts aimed at addressing pricing inequities.</p>
<section id="statistical-testing---phase-1" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="statistical-testing---phase-1"><span class="header-section-number">6.1</span> Statistical Testing - Phase 1</h2>
<p>To consider the impact to different demographics by varying prices for the selected drugs, our team constructed a series of hypotheses. The first consideration was towards race. The majority of U.S. counties contain percentages which heavily tilt towards individuals who identify as white. In fact, when evaluating the percentages across all counties throughout the US, counties are 95% white at the median and 93% at the mean. For our first test, we elected to evaluate counties that were at least 95% white and those below that threshold.</p>
<p>Before proceeding, we had to address assumptions which would be critical to determining which tests could actually apply. We did not initially feel confident applying the assumption of normality to our data. The spread of the median and mean price values across counties and within various medication groups did visually appear normal. However, after applying the Shapiro-Wilk test, Shapiro p-values were all significantly below 0.05 which indicated a lack of normalcy. Accordingly our team chose a non-parametric test to evaluate our hypotheses. The Anderson-Darling test was explored as an alternative to the Shapiro-Wilk test, but the results were similar, with high AD statistic values, suggesting a lack of normality.</p>
<p>The Wilcoxon rank-sum (Mann-Whitney U) test was selected to evaluate two independent groups, specified by the hypothesis threshold. We considered the observations to be independent of each other since the census is completed at the county level, with no counties overlapping.</p>
<p>Ultimately, the Mann-Whitney U Test is less powerful than parametric tests when assumptions are met. It also lacks confidence intervals and is only comparing the ranks and not the actual values. The benefit of taking this approach for our data is that fewer overall assumptions are necessary. Since our team was condensing a number of variables, this approach was preferred to starting with an excessive number of assumptions.</p>
<section id="hypothesis-1" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="hypothesis-1"><span class="header-section-number">6.1.1</span> Hypothesis 1</h3>
<p><em>Null Hypothesis:</em> The distribution of medication costs in counties with &gt;=95% white population is not statistically different from the distribution in counties with &lt;95% white population.</p>
<p><em>Alternative Hypothesis:</em> The distribution of medication costs in counties with &gt;= 95% white population is statistically different from that in counties with &lt;95% white population.</p>
<p><em>Assumptions:</em></p>
<ol type="1">
<li>– Independent groups</li>
<li>– Ordinal or continuous data</li>
<li>– Same Shape of Distribution (when comparing medians)</li>
<li>– Random Sampling</li>
<li>– Independence within each group</li>
</ol>
<p>Accordingly, our team elected to compare mean prices, which notably exposes our analysis to outlier pricing. The assumption independence within each group is stretched, considering the manner in which the data was procured, which we have discussed in great detail.</p>
<div style="font-size: 90%;">
<div id="tbl-h1_pvalue" class="striped hover quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[50,50]">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-h1_pvalue-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Drug Name</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Adalimumab</em></td>
<td><em>3.37e-21</em></td>
</tr>
<tr class="even">
<td><em>Apixaban</em></td>
<td><em>5.46e-21</em></td>
</tr>
<tr class="odd">
<td><em>Insulin Aspart</em></td>
<td><em>6.31e-18</em></td>
</tr>
<tr class="even">
<td><em>Semaglutide</em></td>
<td><em>2.53e-13</em></td>
</tr>
<tr class="odd">
<td><em>Paliperidone Palmitate</em></td>
<td><em>6.19e-13</em></td>
</tr>
<tr class="even">
<td><em>Rivaroxaban</em></td>
<td><em>4.67e-12</em></td>
</tr>
<tr class="odd">
<td><em>Liraglutide</em></td>
<td><em>1.44e-10</em></td>
</tr>
<tr class="even">
<td><em>Empagliflozin</em></td>
<td><em>4.23e-04</em></td>
</tr>
<tr class="odd">
<td><em>Tiotropium Bromide</em></td>
<td><em>1.16e-02</em></td>
</tr>
<tr class="even">
<td><em>Dulaglutide</em></td>
<td><em>1.30e-02</em></td>
</tr>
<tr class="odd">
<td>Lenalidomide</td>
<td>6.55e-02</td>
</tr>
<tr class="even">
<td>Etanercept</td>
<td>7.12e-02</td>
</tr>
<tr class="odd">
<td>Ustekinumab</td>
<td>7.29e-02</td>
</tr>
<tr class="even">
<td>Ibrutinib</td>
<td>4.93e-01</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-h1_pvalue-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: P-value results for Hypothesis 1
</figcaption>
</figure>
</div>
</div>
<p>We can reasonably conclude from this that in 10 of our 14 focus medications, there is a statistically significant difference in mean prices and reject the null hypothesis for these medications. (See <a href="#tbl-h1_pvalue" class="quarto-xref">Table&nbsp;2</a> above.) To dive deeper, our team constructed density plots to compare the direction of this difference. As observed in <a href="#fig-h1" class="quarto-xref">Figure&nbsp;8</a>, where we evaluate two of these medications, Semaglutide and Dulaglutide. We can see that the direction shifts at different price ranks and the shift depends on the medication.</p>
<div id="cell-fig-h1" class="cell">
<div class="cell-output-display">
<div id="fig-h1" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-h1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-h1-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-8" title="Figure&nbsp;8: Hypothesis 1 - Comparing GLP-1 receptor agonists, primarily used for type 2 diabetes management"><img src="capstone_files/figure-html/fig-h1-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-h1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8: Hypothesis 1 - Comparing GLP-1 receptor agonists, primarily used for type 2 diabetes management
</figcaption>
</figure>
</div>
</div>
</div>
<p>Drilling down again, with these two medications in focus, actual values are compared below in <a href="#tbl-h1_means" class="quarto-xref">Table&nbsp;3</a>.</p>
<div style="font-size: 90%;">
<div id="tbl-h1_means" class="striped hover quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[25,25,25,25]">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-h1_means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover table">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Drug Name</th>
<th>&gt;=95% White</th>
<th>Mean of Mean Price</th>
<th>SD Mean Price</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Dulaglutide</td>
<td>FALSE</td>
<td>444.00</td>
<td>3.74</td>
</tr>
<tr class="even">
<td>Dulaglutide</td>
<td>TRUE</td>
<td>444.00</td>
<td>3.71</td>
</tr>
<tr class="odd">
<td>Semaglutide</td>
<td>FALSE</td>
<td>168.00</td>
<td>2.58</td>
</tr>
<tr class="even">
<td>Semaglutide</td>
<td>TRUE</td>
<td>167.00</td>
<td>1.84</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-h1_means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Mean of Mean Price and Standard Deviation for Dulaglutide and Semaglutide betwen two race groups
</figcaption>
</figure>
</div>
</div>
<p>The findings are interesting but have issues. In the plot, we can clearly see that slight advantages are given to certain groups at certain prices. The mean of the mean prices, as well as the standard deviations show practically no difference for Dulaglutide and only some difference for Semaglutide. Unfortunately, this does not provide much clarity regarding any particular advantage afforded to counties where more than 95% of the population identifies as white. The findings are hardly definitive and lack confidence intervals. This does demonstrate the limitations of using the Mann-Whitney U Test.</p>
</section>
<section id="hypothesis-2" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="hypothesis-2"><span class="header-section-number">6.1.2</span> Hypothesis 2</h3>
<p>Using the same assumptions, another consideration involves fully removing the racial aspect and instead considering the percentage of the population that is below the poverty level. Within the census data, the median is 13% below the poverty level, across all counties and 14% at the mean. We establish a new hypothesis.</p>
<p><em>Null Hypothesis:</em> The distribution of medication costs in counties with &gt;=13% below poverty population is not statistically different from the distribution in counties with &lt;13% below poverty population.</p>
<p><em>Alternative Hypothesis:</em> The distribution of medication costs in counties with &gt;= 13% below poverty population is statistically different from that in counties with &lt;13% below poverty population.</p>
<div style="font-size: 90%;">
<div id="tbl-h2_pvalue" class="striped hover quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[50,50]">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-h2_pvalue-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Drug Name</th>
<th>p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>Semaglutide</em></td>
<td><em>1.43e-20</em></td>
</tr>
<tr class="even">
<td><em>Dulaglutide</em></td>
<td><em>2.49e-16</em></td>
</tr>
<tr class="odd">
<td><em>Ibrutinib</em></td>
<td><em>4.41e-13</em></td>
</tr>
<tr class="even">
<td><em>Insulin Aspart</em></td>
<td><em>2.34e-10</em></td>
</tr>
<tr class="odd">
<td><em>Adalimumab</em></td>
<td><em>3.46e-10</em></td>
</tr>
<tr class="even">
<td><em>Etanercept</em></td>
<td><em>2.40e-08</em></td>
</tr>
<tr class="odd">
<td><em>Ustekinumab</em></td>
<td><em>8.88e-08</em></td>
</tr>
<tr class="even">
<td><em>Apixaban</em></td>
<td><em>1.90e-06</em></td>
</tr>
<tr class="odd">
<td><em>Empagliflozin</em></td>
<td><em>6.70e-06</em></td>
</tr>
<tr class="even">
<td><em>Liraglutide</em></td>
<td><em>1.12e-03</em></td>
</tr>
<tr class="odd">
<td><em>Lenalidomide</em></td>
<td><em>1.43e-03</em></td>
</tr>
<tr class="even">
<td><em>Paliperidone Palmitate</em></td>
<td><em>2.70e-02</em></td>
</tr>
<tr class="odd">
<td>Tiotropium Bromide</td>
<td>8.55e-02</td>
</tr>
<tr class="even">
<td>Rivaroxaban</td>
<td>1.54e-01</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-h2_pvalue-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: P-value results for Hypothesis 2
</figcaption>
</figure>
</div>
</div>
<p>Again, we find that there are statistically significant outcomes for many of the selected medications. Twelve of the fourteen medications yield p-values below 0.05 suggesting that the null hypothesis be rejected. (See <a href="#tbl-h2_pvalue" class="quarto-xref">Table&nbsp;4</a> above.)</p>
<p>In <a href="#fig-h2" class="quarto-xref">Figure&nbsp;9</a> we look closer at six medications, to expand the investigation into these differences and the direction of any potential advantage.</p>
<div id="cell-fig-h2" class="cell">
<div class="cell-output-display">
<div id="fig-h2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-h2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-h2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-9" title="Figure&nbsp;9: Hypothesis 2 - Comparing medications which were indicated for statistically significant differences in price for two poverty groups"><img src="capstone_files/figure-html/fig-h2-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-h2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;9: Hypothesis 2 - Comparing medications which were indicated for statistically significant differences in price for two poverty groups
</figcaption>
</figure>
</div>
</div>
</div>
<p>Similar to hypothesis 1, we see that the price differences are contextual to the medication and price rank position. While the null hypothesis is rejected, the challenge of approaching multiple medications is clearly demonstrated. For both hypotheses, by rejecting the null, this may result in a type 1 error, or false positive. There are clearly price differences relative to certain demographic groups. Whether those differences are being driven by the demographics remained unclear.</p>
</section>
</section>
<section id="statistical-testing---phase-2" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="statistical-testing---phase-2"><span class="header-section-number">6.2</span> Statistical Testing - Phase 2</h2>
<p>In order to further explore statistical significance, we assumed a normal distribution of the data. This assumption enabled the use of traditional parametric testing methods. Specifically, we conducted two-sample t-tests, mirroring the structure used in the first phase of statistical testing, where the dataset was divided based on demographic medians. Additionally, we grouped counties into multiple subsets using demographic quartiles rather than medians, allowing for more granular comparisons. This stratification enabled the application of the Tukey HSD test to assess pairwise differences across these groups.</p>
<p>Using a two-sample t-test allowed reconsideration of our second hypothesis. We again encountered low p-values. Selecting for Semaglutide as one example and using the same data split for poverty at the median, the resulting p-value was 2.2e-16 which was a strong indicator for statistical significance, suggesting we reject the null.</p>
<p>Building on this, we applied the Tukey HSD test to the quartile-based groups at a 95% confidence level. Again, we found p-values that supported rejecting the null hypothesis, indicating that the average mean prices across groups were not equal. Interestingly, the only comparisons with p-values at or above 5% occurred between adjacent quartile groups, while all other comparisons yielded p-values well below this threshold. (See <a href="#tbl-p2_tukey" class="quarto-xref">Table&nbsp;5</a> below.)</p>
<div style="font-size: 90%;">
<div id="tbl-p2_tukey" class="striped hover quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[40, 15, 15, 15, 15]">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-p2_tukey-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover table">
<colgroup>
<col style="width: 40%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Comparison</th>
<th>Difference</th>
<th>Lower CI</th>
<th>Upper CI</th>
<th>Adjusted p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&gt;17% Poverty - 0-10% Poverty</td>
<td>-1.1555147</td>
<td>-1.4430153</td>
<td>-0.8680141</td>
<td>0.0000000</td>
</tr>
<tr class="even">
<td>&gt;17% Poverty - 10-13% Poverty</td>
<td>-0.8564752</td>
<td>-1.1503721</td>
<td>-0.5625784</td>
<td>0.0000000</td>
</tr>
<tr class="odd">
<td>&gt;17% Poverty - 13-17% Poverty</td>
<td>-0.6371890</td>
<td>-0.9262280</td>
<td>-0.3481500</td>
<td>0.0000001</td>
</tr>
<tr class="even">
<td>13-17% Poverty - 0-10% Poverty</td>
<td>-0.5183257</td>
<td>-0.8123963</td>
<td>-0.2242551</td>
<td>0.0000361</td>
</tr>
<tr class="odd">
<td>10-13% Poverty - 0-10% Poverty</td>
<td>-0.2990395</td>
<td>-0.5978861</td>
<td>-0.0001928</td>
<td>0.0497806</td>
</tr>
<tr class="even">
<td>13-17% Poverty - 10-13% Poverty</td>
<td>-0.2192862</td>
<td>-0.5196131</td>
<td>0.0810407</td>
<td>0.2382320</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-p2_tukey-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Tukey HSD test comparing Semaglutide prices amongst four poverty levels
</figcaption>
</figure>
</div>
</div>
<p>We repeated this process across several medications and demographic variables, consistently observing statistical significance. However, when examining the actual differences in average prices between groups, the magnitude of these differences was often minimal. Continuing with Semaglutide as an example, counties in the lowest poverty quartile (0–10%) had an average mean price of $168, while those in the highest poverty quartile (&gt;17%) had an average of $167, a mere $1 difference. Notably, counties with higher poverty levels were paying slightly less on average.</p>
<p>To better understand the implications of this finding, we considered affordability by dividing the mean price by the median income of each county. This revealed that although prices were lower in higher-poverty areas, the cost represented a larger proportion of income, highlighting a disparity in affordability. This relationship is clearly illustrated in the following <a href="#tbl-p2-means" class="quarto-xref">Table&nbsp;6</a> and <a href="#fig-h2_2" class="quarto-xref">Figure&nbsp;10</a>.</p>
<div style="font-size: 90%;">
<div id="tbl-p2-means" class="striped hover quarto-float quarto-figure quarto-figure-center anchored" data-tbl-colwidths="[30, 14, 14, 14, 14]">
<figure class="quarto-float quarto-float-tbl figure">
<div aria-describedby="tbl-p2-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover table">
<colgroup>
<col style="width: 30%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Poverty Group</th>
<th>Mean Price</th>
<th>SD Price</th>
<th>Mean Affordability</th>
<th>SD Affordability</th>
<th>Sample Size (n)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0–10% Poverty</td>
<td>168.00</td>
<td>2.35</td>
<td>0.00209</td>
<td>0.000409</td>
<td>788</td>
</tr>
<tr class="even">
<td>10–13% Poverty</td>
<td>168.00</td>
<td>2.60</td>
<td>0.00246</td>
<td>0.000332</td>
<td>725</td>
</tr>
<tr class="odd">
<td>13–17% Poverty</td>
<td>167.00</td>
<td>2.36</td>
<td>0.00275</td>
<td>0.000351</td>
<td>772</td>
</tr>
<tr class="even">
<td>&gt;17% Poverty</td>
<td>167.00</td>
<td>1.69</td>
<td>0.00340</td>
<td>0.000613</td>
<td>846</td>
</tr>
</tbody>
</table>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-tbl" id="tbl-p2-means-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Mean and standard deviation of prices of Semaglutide by four poverty buckets
</figcaption>
</figure>
</div>
</div>
<div id="cell-fig-h2_2" class="cell">
<div class="cell-output-display">
<div id="fig-h2_2" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-h2_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-h2_2-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-10" title="Figure&nbsp;10: Parametric Testing - Exploring affordability for Semaglutide across various levels of poverty"><img src="capstone_files/figure-html/fig-h2_2-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-h2_2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;10: Parametric Testing - Exploring affordability for Semaglutide across various levels of poverty
</figcaption>
</figure>
</div>
</div>
</div>
<p>We employed both t-tests and Tukey HSD tests to evaluate a range of medications across various demographic subsets, tailoring each analysis to specific hypotheses about potential demographic impacts on drug pricing. While many results showed statistical significance, further inspection revealed that the actual differences in mean prices, affordability metrics, and other summary statistics were often marginal.</p>
<p>This distinction between statistical and practical significance became a turning point. Statistical significance simply indicates that a result is unlikely due to random chance. It does not guarantee that the difference is meaningful or actionable. In our case, the detected differences, though statistically valid, lacked the magnitude necessary to inform policy or guide consumer decisions.</p>
<p>Recognizing this limitation, we pivoted our focus toward structural market factors, particularly the relationship between population size and the number of available Medicare Part D plans in each county. This shift allowed us to explore whether plan availability aligns with population needs, a perspective that offers more tangible insights into affordability and access. By emphasizing market dynamics over demographic predictors, we uncovered patterns that more directly influence pricing and equity across regions.</p>
</section>
<section id="population-vs-number-of-available-medicare-plans" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="population-vs-number-of-available-medicare-plans"><span class="header-section-number">6.3</span> Population vs Number of Available Medicare Plans</h2>
<p>Given the lack of clear patterns for medication prices across the maps and within isolated demographic groups, we turned to a deep dive into the demographics. Our first dive was into the population. Do counties with a larger population have more Medicare plan options, and does this competition lead to lower drug prices? A scatter plot of the number of Medicare Plans available vs the population per county is shown below with a linear fit to show a trend line in <a href="#fig-plans-vs-population" class="quarto-xref">Figure&nbsp;11</a>.</p>
<div id="cell-fig-plans-vs-population" class="cell">
<div class="cell-output-display">
<div id="fig-plans-vs-population" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plans-vs-population-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-plans-vs-population-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-11" title="Figure&nbsp;11: Correlation between the number of Medicare Plan Options and Total Population by US County in 23Q4"><img src="capstone_files/figure-html/fig-plans-vs-population-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plans-vs-population-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;11: Correlation between the number of Medicare Plan Options and Total Population by US County in 23Q4
</figcaption>
</figure>
</div>
</div>
</div>
<p>While there is a slight trend, it is not a great fit overall. The model is statistically significant (p-value &lt; 0.05) and shows a moderate positive relationship (slope = 0.0195, or 1 more medicare plan with a 1.95% increase in the population) between the number of Medicare plans and population. But it’s not a strong fit. Two-thirds of the variation in population is left unexplained (adjusted R-squared = 0.3444), so we don’t want to over-interpret this model as being predictive. Given the limited correlation between the number of available plans and population, we don’t think this demographic measure is having much of an impact on medication prices.</p>
<p>From here, we jumped into creating a model across all our demographics (age, education, gender, and racial breakdowns, as well as median income, and percent below the poverty line).</p>
</section>
<section id="machine-learning" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="machine-learning"><span class="header-section-number">6.4</span> Machine Learning</h2>
<section id="model-selection" class="level3" data-number="6.4.1">
<h3 data-number="6.4.1" class="anchored" data-anchor-id="model-selection"><span class="header-section-number">6.4.1</span> Model Selection</h3>
<p>In order to model the relationship between medication prices and demographic features, we employed a variety of machine learning algorithms, each with unique strengths and assumptions. Below is a brief overview of the algorithms explored:</p>
<p><strong>Linear Model (LM):</strong> Linear regression is a fundamental technique used to model the relationship between a continuous outcome variable and one or more predictors, assuming a linear relationship. It is interpretable and computationally efficient but may underperform when the underlying patterns are nonlinear or complex.</p>
<p><strong>Elastic Net (ENET):</strong> Elastic Net is a regularized regression method that combines both L1 (Lasso) and L2 (Ridge) penalties. It is particularly effective when dealing with multicollinearity or when performing variable selection in high-dimensional datasets. Elastic Net encourages sparsity while maintaining group stability among correlated features.</p>
<p><strong>Gradient Boosting Machine (GBM):</strong> GBM is an ensemble technique that builds models sequentially, with each new model correcting the errors of the previous one. It is capable of capturing complex nonlinear relationships and is known for its high predictive performance, although it can be prone to overfitting if not properly tuned.</p>
<p><strong>K-Nearest Neighbors (KNN):</strong> KNN is a non-parametric algorithm that classifies or predicts outcomes based on the average value (or majority class) of the k closest observations in the feature space. It is simple and intuitive but can struggle with high-dimensional data and is sensitive to the choice of distance metric and value of k.</p>
<p><strong>Random Forest (RF):</strong> Random Forest is an ensemble method that constructs a large number of decision trees during training and outputs the average prediction (for regression) or majority vote (for classification). It offers good performance with low risk of overfitting, handles missing data well, and provides insights into feature importance.</p>
<p><strong>Support Vector Machine (SVM):</strong> SVM is a powerful classifier and regressor that aims to find the optimal hyperplane that maximally separates classes or fits data with minimal error (via support vectors). It works well in high-dimensional spaces and with complex boundaries but can be computationally intensive and sensitive to kernel and parameter choices.</p>
<p><strong>Extreme Gradient Boosting (XGBoost):</strong> XGBoost is an optimized and scalable implementation of gradient boosting. It includes advanced features such as regularization, parallel processing, and handling of missing values. XGBoost typically outperforms many other algorithms in structured data problems and is widely used in machine learning competitions and real-world applications.</p>
</section>
<section id="model-performance" class="level3" data-number="6.4.2">
<h3 data-number="6.4.2" class="anchored" data-anchor-id="model-performance"><span class="header-section-number">6.4.2</span> Model Performance</h3>
<p>Looping over every drug, we trained all the previously described models. A heatmap of the resulting model performance is provided below in <a href="#fig-heatmap-models-performance" class="quarto-xref">Figure&nbsp;12</a>. As expected, the gradient boosting machine, the random forest, and the extreme gradient boosting models performed the best across all drugs. Unfortunately, while the models have ok R<sup>2</sup> values when fitting to the training data, the R<sup>2</sup> values for the test data is significantly lower. This suggests that the models are overfitting to the training data, and we need to tune the hyperparameters of the models to improve performance.</p>
<div id="cell-fig-heatmap-models-performance" class="cell">
<div class="cell-output-display">
<div id="fig-heatmap-models-performance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heatmap-models-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-heatmap-models-performance-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-12" title="Figure&nbsp;12: Model Performance Heatmap by Drug"><img src="capstone_files/figure-html/fig-heatmap-models-performance-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-heatmap-models-performance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;12: Model Performance Heatmap by Drug
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="tuning-to-prevent-overfitting" class="level3" data-number="6.4.3">
<h3 data-number="6.4.3" class="anchored" data-anchor-id="tuning-to-prevent-overfitting"><span class="header-section-number">6.4.3</span> Tuning to Prevent Overfitting</h3>
<p>To improve the model performance and prevent overfitting, we tuned the hyperparameters of the extreme gradient boosting models. The tuning process involved adjusting parameters such as the number of rounds, maximum depth, learning rate (aka eta) and more to optimize model performance on the validation set. Our most overfit model, XGB6, has a nearly perfect fit to the training data for all drugs, and yet it also has the best fit to the test data. If the model had the appropriate key features that drive median price, we would’ve expected to see the test R<sup>2</sup> values much closer to the training R^2 values. There would be a optimum point where the training data might have a worse fit, but the test data would have a better fit in comparison. Tuning the parameters to prevent overfitting, you can see the XGB7, XGB8, and XGB9 get progressively worse fits to the training data, but also those models get worse fits to the test data. Thus, we think that the features that we have are not the best predictors of median drug price. The performance of the tuned XGB models are shown in <a href="#fig-heatmap-models-performance-tuned" class="quarto-xref">Figure&nbsp;13</a>.</p>
<div id="cell-fig-heatmap-models-performance-tuned" class="cell">
<div class="cell-output-display">
<div id="fig-heatmap-models-performance-tuned" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heatmap-models-performance-tuned-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-heatmap-models-performance-tuned-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="Figure&nbsp;13: Tuned XGB Models Performance Heatmap by Drug"><img src="capstone_files/figure-html/fig-heatmap-models-performance-tuned-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-heatmap-models-performance-tuned-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;13: Tuned XGB Models Performance Heatmap by Drug
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="feature-importance" class="level3" data-number="6.4.4">
<h3 data-number="6.4.4" class="anchored" data-anchor-id="feature-importance"><span class="header-section-number">6.4.4</span> Feature Importance</h3>
<p>The most important features for the initial XGB model across all drugs are shown in the heatmap below (<a href="#fig-heatmap-rf-variable-importance" class="quarto-xref">Figure&nbsp;14</a>). The most obvious pattern here is that the num_contract_plans (aka the quantity of available Medicare plans) is the most important feature for 12 out of the 14 top drugs. We already looked at the connection between total_] population and the quantity of available plans in a county previously, and only saw a mild correlation. For the other two drugs, the top features were income per capita and percent of the population with master’s degree.</p>
<div id="cell-fig-heatmap-rf-variable-importance" class="cell">
<div class="cell-output-display">
<div id="fig-heatmap-rf-variable-importance" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-heatmap-rf-variable-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-heatmap-rf-variable-importance-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="Figure&nbsp;14: Top 5 Variable Importance Heatmap by Drug for XGB Model"><img src="capstone_files/figure-html/fig-heatmap-rf-variable-importance-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-heatmap-rf-variable-importance-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14: Top 5 Variable Importance Heatmap by Drug for XGB Model
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="feature-direction" class="level3" data-number="6.4.5">
<h3 data-number="6.4.5" class="anchored" data-anchor-id="feature-direction"><span class="header-section-number">6.4.5</span> Feature Direction</h3>
<p>To determine if more Medicare plan options in a county increase or decrease the drug price, we did a quick linear regression fit between the median price of all drugs and the number of available Medicare plans in a county. The results are shown in <a href="#fig-effect-available-plans-on-drug-price" class="quarto-xref">Figure&nbsp;15</a> below. The percent of the price variance that is due to the number of available Medicare plans was pulled from the R<sup>2</sup> value and is shown in the size of the points. The direction of the relationship is shown as a percent of the median drug price on the X-axis. For every 10 medicare plans added to a county, the drug price either increases or decreases by the percent in the plot. The significance of the relationship was determined by a p-value &lt; 0.05 and is color coded in the plot. For the most affected drug price, the number of contracts accounts for up to ~5% of the variance in drug price. 5% is not a very large imcpart. Also, some drugs are increasing price and some decreasing with the addition of 10 more Medicare plan options in a county. In general, the number of Medicare plans, along with demographics, aren’t the only factor that drives drug price, but the number of plans is the most important factor we found in our feature set.</p>
<div id="cell-fig-effect-available-plans-on-drug-price" class="cell">
<div class="cell-output-display">
<div id="fig-effect-available-plans-on-drug-price" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-effect-available-plans-on-drug-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="capstone_files/figure-html/fig-effect-available-plans-on-drug-price-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15" title="Figure&nbsp;15: Effect of Additional Available Medicare Plans in a County on Drug Price"><img src="capstone_files/figure-html/fig-effect-available-plans-on-drug-price-1.png" class="img-fluid figure-img" style="width:100.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-effect-available-plans-on-drug-price-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;15: Effect of Additional Available Medicare Plans in a County on Drug Price
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="machine-learning-conclusions" class="level3" data-number="6.4.6">
<h3 data-number="6.4.6" class="anchored" data-anchor-id="machine-learning-conclusions"><span class="header-section-number">6.4.6</span> Machine Learning Conclusions</h3>
<p>The application of diverse machine learning algorithms provided valuable insights into the complex relationships between demographic factors and medication prices across U.S. counties. Despite the initial hypothesis that demographic variables might strongly predict drug pricing disparities, our results indicate that the quantity of Medicare plans available within a county is the most consistent and influential predictor across the majority of the top-spending medications. Other demographic features, such as education level, income, and racial composition, showed variable importance depending on the specific drug but did not emerge as universally strong predictors.</p>
<p>The superior performance of GBM, RF, and XGB models highlights the nonlinear and multifaceted nature of drug pricing patterns, which simpler linear models struggled to capture effectively. This complexity underscores the challenge of modeling medication prices purely based on demographics and points to the potential influence of additional factors not captured in our current dataset.</p>
<p>Overall, these findings suggest that while demographic characteristics contribute to medication price variation, market dynamics (reflected by Medicare plan availability) play a pivotal role. Future work may benefit from incorporating additional economic, regulatory, and supply-chain data to better explain and predict geographic disparities in medication costs. This knowledge could ultimately inform policies aimed at improving affordability and equity in drug pricing.</p>
</section>
</section>
</section>
<section id="conclusions" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Conclusions</h1>
<section id="insights-and-recommendations" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="insights-and-recommendations"><span class="header-section-number">7.1</span> Insights and Recommendations</h2>
<p>Our analysis reveals significant geographic disparities in Medicare Part D drug pricing across the United States. While our data does not conclusively demonstrate that these pricing variations disproportionately affect any single demographic group, the inconsistencies raise serious concerns about the effectiveness and equity of Medicare’s price negotiation mechanisms. The observed variation suggests that drug costs could be more uniformly regulated, pointing to inefficiencies in the current system.</p>
<p>For many Medicare beneficiaries, particularly older adults and individuals with limited financial resources, the challenge of navigating complex plan options to secure affordable coverage remains significant. Despite the availability of plan finder tools and licensed advisors, the process is often overwhelming for the very population the program is designed to support. This complexity undermines both the accessibility and fairness of Medicare Part D, highlighting a need for more user-friendly systems and clearer guidance to ensure equitable and affordable access to prescription drug coverage.</p>
<p>The Inflation Reduction Act of 2022 represents a pivotal step toward addressing the long-standing issue of unsustainable drug pricing in the United States. Regulatory actions by the U.S. Department of Health and Human Services (HHS) and the Centers for Medicare &amp; Medicaid Services (CMS) <span class="citation" data-cites="cms2025negotiation">(<a href="#ref-cms2025negotiation" role="doc-biblioref">Centers for Medicare &amp; Medicaid Services 2024b</a>)</span> have demonstrated promising potential to curb excessive price increases. Notably, in December 2024, CMS <span class="citation" data-cites="cms2024inflationrebate">(<a href="#ref-cms2024inflationrebate" role="doc-biblioref">Centers for Medicare &amp; Medicaid Services 2024a</a>)</span> announced cost savings for 64 drugs whose prices had risen faster than inflation, an encouraging indicator of progress.</p>
<p>However, the full impact of these measures remains to be seen. Much of the projected savings will not be realized until 2026, and their effectiveness will depend on several factors, including pharmaceutical industry responses, future pricing trends, and the extent to which the affected medications are utilized by beneficiaries. Continued monitoring and evaluation will be essential to ensure these reforms translate into meaningful improvements in affordability and access.</p>
<p>To promote greater equity and transparency in Medicare Part D, federal and state policymakers could collaborate to ensure that the lowest negotiated drug prices are made broadly accessible, rather than restricted to specific plans or contracts. This approach presents a clear opportunity to advance price normalization and improve the visibility of treatment costs. By making pricing more consistent and transparent, policymakers can better serve Medicare beneficiaries and reinforce the integrity and fairness of the program.</p>
<p>Price normalization across Medicare Part D plans could yield far-reaching benefits that extend beyond the immediate Medicare population. By reducing regional and plan-based disparities, normalization would foster a more predictable and equitable pricing environment for all stakeholders, including healthcare providers, pharmacies, and insurers. It could also streamline administrative processes by minimizing the complexity of managing varied pricing structures, thereby enhancing the efficiency of healthcare delivery and reducing operational costs.</p>
<p>Fortunately, many private companies (like GoodRx and CostPlusDrugs) are actively working to promote price transparency and secure the best possible prices for commonly prescribed medications. Their efforts demonstrate that innovation in medication pricing structures is feasible. Policymakers must embrace these emerging modern approaches and support initiatives that promote consistent and transparent pricing across the healthcare system. This is not about enforcing rigid price controls, but rather about ensuring fairness, clarity, and accessibility in how drug prices are determined and communicated.</p>
<p>Normalized drug pricing across Medicare Part D plans could play a critical role in curbing overall healthcare spending by discouraging price inflation and fostering competitive pricing among pharmaceutical manufacturers. When prices are consistent and transparent, it becomes significantly easier for policymakers, researchers, and healthcare administrators to evaluate cost-effectiveness, identify inefficiencies, and implement targeted reforms. This clarity can lead to more strategic resource allocation, improved public health outcomes, and a more sustainable healthcare system.</p>
<p>The movement toward transparent and normalized drug pricing offers a promising path forward for consumers and the healthcare system alike. With private companies paving the way, policymakers have a unique chance to foster a more equitable pricing landscape, one built on clarity, consistency, and shared benefit.</p>
</section>
<section id="ethical-considerations" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="ethical-considerations"><span class="header-section-number">7.2</span> Ethical Considerations</h2>
<section id="equity-and-fairness" class="level3" data-number="7.2.1">
<h3 data-number="7.2.1" class="anchored" data-anchor-id="equity-and-fairness"><span class="header-section-number">7.2.1</span> Equity and Fairness</h3>
<p>Leveraging census data introduces inherent biases, as certain populations, such as undocumented individuals, transient communities, or those with limited access to digital infrastructure, may be underrepresented. Throughout our data collection, cleaning, and analysis processes, we have taken deliberate steps to avoid stigmatizing or overgeneralizing any group.</p>
<p>We recognize that systemic disparities in healthcare access, driven by socioeconomic status, geography, race, and other factors, can influence both the availability and affordability of medications. Additionally, using Medicare pricing as a proxy for broader drug costs may obscure trends that would be more visible with commercial or retail pricing data. This methodological choice, while practical, may limit the general applicability of our findings and should be interpreted with caution.</p>
</section>
<section id="purpose-and-impact" class="level3" data-number="7.2.2">
<h3 data-number="7.2.2" class="anchored" data-anchor-id="purpose-and-impact"><span class="header-section-number">7.2.2</span> Purpose and Impact</h3>
<p>The primary goal of this project is to contribute to a more equitable and transparent healthcare system in the United States. By linking CMS formulary data with demographic insights from the census, we aim to uncover patterns that can inform future research, policy development, and targeted interventions. We hope that this work serves as a foundation for ongoing efforts to address longstanding inequities in healthcare accessibility and affordability.</p>
</section>
<section id="privacy" class="level3" data-number="7.2.3">
<h3 data-number="7.2.3" class="anchored" data-anchor-id="privacy"><span class="header-section-number">7.2.3</span> Privacy</h3>
<p>All data used in this project was sourced from publicly available datasets that do not contain personally identifiable information. No attempt was made to re-identify individuals through data linkage or analysis. Our approach prioritizes responsible data handling and respects the privacy of all individuals that might be represented.</p>
</section>
</section>
<section id="future-research" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="future-research"><span class="header-section-number">7.3</span> Future Research</h2>
<p>One of the most significant challenges encountered in this project was the sheer size and complexity of the datasets. To make the analysis feasible, data had to be condensed and aggregated, which limited the granularity of insights. However, this also highlights the substantial potential for deeper and more nuanced analysis using these connected datasets in future work.</p>
<section id="longitudinal-analysis" class="level3" data-number="7.3.1">
<h3 data-number="7.3.1" class="anchored" data-anchor-id="longitudinal-analysis"><span class="header-section-number">7.3.1</span> Longitudinal Analysis</h3>
<p>The CMS formulary data that was collected is published quarterly, offering a valuable opportunity to evaluate trends over time. Future research could explore:</p>
<ul>
<li>Price fluctuations within specific contracts and plans.</li>
<li>Temporal shifts in drug availability or coverage.</li>
<li>Policy impacts on pricing and access over time. This longitudinal approach could reveal how changes in healthcare policy, market dynamics, or demographic shifts influence drug pricing and accessibility.</li>
</ul>
</section>
<section id="expanded-demographic-analysis" class="level3" data-number="7.3.2">
<h3 data-number="7.3.2" class="anchored" data-anchor-id="expanded-demographic-analysis"><span class="header-section-number">7.3.2</span> Expanded Demographic Analysis</h3>
<p>While this project incorporated basic demographic overlays, future work could benefit from:</p>
<ul>
<li>More granular demographic segmentation.</li>
<li>Intersectional analysis to understand how overlapping identities affect access to medications and plan availability.</li>
</ul>
</section>
<section id="geographic-and-environmental-context" class="level3" data-number="7.3.3">
<h3 data-number="7.3.3" class="anchored" data-anchor-id="geographic-and-environmental-context"><span class="header-section-number">7.3.3</span> Geographic and Environmental Context</h3>
<p>Incorporating spatial and environmental factors could enhance understanding of healthcare access disparities:</p>
<ul>
<li>Rural vs.&nbsp;urban classifications to assess geographic inequities in drug coverage and pricing.</li>
<li>Healthcare infrastructure mapping, such as proximity to pharmacies or providers, to contextualize formulary access.</li>
</ul>
</section>
<section id="sociopolitical-context" class="level3" data-number="7.3.4">
<h3 data-number="7.3.4" class="anchored" data-anchor-id="sociopolitical-context"><span class="header-section-number">7.3.4</span> Sociopolitical Context</h3>
<p>Exploring the influence of sociopolitical factors could add depth to the analysis:</p>
<ul>
<li>Political leanings of regions (e.g., voting patterns) to examine correlations with healthcare policy adoption or plan availability.</li>
<li>State-level policy differences, such as Medicaid expansion or drug pricing regulations, to assess their impact on formulary design.</li>
</ul>
</section>
</section>
</section>
<section id="references" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> References</h1>
<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-TCF2025" class="csl-entry" role="listitem">
<span>“2025 Scorecard on State Health System Performance, Fragile Progress, Continuing Disparities.”</span> 2025. <a href="https://www.commonwealthfund.org/publications/scorecard/2025/jun/2025-scorecard-state-health-system-performance">https://www.commonwealthfund.org/publications/scorecard/2025/jun/2025-scorecard-state-health-system-performance</a>.
</div>
<div id="ref-cms2024inflationrebate" class="csl-entry" role="listitem">
Centers for Medicare &amp; Medicaid Services. 2024a. <span>“HHS Announces Cost Savings for 64 Prescription Drugs Thanks to Medicare Prescription Drug Inflation Rebate.”</span> <a href="https://www.cms.gov/newsroom/press-releases/hhs-announces-cost-savings-64-prescription-drugs-thanks-medicare-prescription-drug-inflation-rebate">https://www.cms.gov/newsroom/press-releases/hhs-announces-cost-savings-64-prescription-drugs-thanks-medicare-prescription-drug-inflation-rebate</a>.
</div>
<div id="ref-cms2025negotiation" class="csl-entry" role="listitem">
———. 2024b. <span>“Medicare Drug Price Negotiation Program: Negotiated Prices for Initial Price Applicability Year 2026.”</span> <a href="https://www.cms.gov/newsroom/fact-sheets/medicare-drug-price-negotiation-program-negotiated-prices-initial-price-applicability-year-2026">https://www.cms.gov/newsroom/fact-sheets/medicare-drug-price-negotiation-program-negotiated-prices-initial-price-applicability-year-2026</a>.
</div>
<div id="ref-cms2025data" class="csl-entry" role="listitem">
———. 2025. <span>“CMS Data Navigator.”</span> <a href="https://data.cms.gov/">https://data.cms.gov/</a>.
</div>
<div id="ref-costplusdrugs2025" class="csl-entry" role="listitem">
Cost Plus Drugs. 2025. <span>“Cost Plus Drugs: Prescription Medications at Fair Prices.”</span> <a href="https://www.costplusdrugs.com/">https://www.costplusdrugs.com/</a>.
</div>
<div id="ref-countiesConnecticut" class="csl-entry" role="listitem">
Federal Register: The Daily Journal of the United States Government. 2022. <span>“Change to County-Equivalents in the State of Connecticut.”</span> <a href="https://www.federalregister.gov/documents/2022/06/06/2022-12063/change-to-county-equivalents-in-the-state-of-connecticut">https://www.federalregister.gov/documents/2022/06/06/2022-12063/change-to-county-equivalents-in-the-state-of-connecticut</a>.
</div>
<div id="ref-gellad2009variation" class="csl-entry" role="listitem">
Gellad, Walid F., Niteesh K. Choudhry, Mark W. Friedberg, M. Alan Brookhart, Jennifer S. Haas, and William H. Shrank. 2009. <span>“Variation in Drug Prices at Pharmacies: Are Prices Higher in Poorer Areas?”</span> <em>Health Services Research</em> 44 (2 Pt 1): 606–17. <a href="https://doi.org/10.1111/j.1475-6773.2008.00917.x">https://doi.org/10.1111/j.1475-6773.2008.00917.x</a>.
</div>
<div id="ref-goodrx2025" class="csl-entry" role="listitem">
GoodRx. 2025. <span>“GoodRx: Prescription Drug Prices and Coupons.”</span> <a href="https://www.goodrx.com">https://www.goodrx.com</a>.
</div>
<div id="ref-medicarePartDCosts" class="csl-entry" role="listitem">
Medicare.gov. 2025a. <span>“How Much Does Medicare Drug Coverage Cost?”</span> <a href="https://www.medicare.gov/health-drug-plans/part-d/basics/costs">https://www.medicare.gov/health-drug-plans/part-d/basics/costs</a>.
</div>
<div id="ref-medicareParts" class="csl-entry" role="listitem">
———. 2025b. <span>“Parts of Medicare.”</span> <a href="https://www.medicare.gov/basics/get-started-with-medicare/medicare-basics/parts-of-medicare">https://www.medicare.gov/basics/get-started-with-medicare/medicare-basics/parts-of-medicare</a>.
</div>
<div id="ref-ncbi_nbk493090" class="csl-entry" role="listitem">
National Academies of Sciences, Engineering, and Medicine; Health and Medicine Division; Board on Health Care Services; Committee on Ensuring Patient Access to Affordable Drug Therapies; 2017. <span>“Making Medicines Affordable: A National Imperative.”</span> In, edited by Augustine NR Nass SJ Madhavan G. National Academies Press (US). <a href="https://www.ncbi.nlm.nih.gov/books/NBK493090/">https://www.ncbi.nlm.nih.gov/books/NBK493090/</a>.
</div>
<div id="ref-KFF2024" class="csl-entry" role="listitem">
<span>“Public Opinion on Prescription Drugs and Their Prices.”</span> 2024. <a href="https://www.kff.org/health-costs/poll-finding/public-opinion-on-prescription-drugs-and-their-prices/">https://www.kff.org/health-costs/poll-finding/public-opinion-on-prescription-drugs-and-their-prices/</a>.
</div>
<div id="ref-unc2025semaglutide" class="csl-entry" role="listitem">
UNC Health. 2025. <span>“Study Finds Oral Semaglutide Vastly Reduces Heart Attacks, Strokes.”</span> 2025. <a href="https://news.unchealthcare.org/2025/03/study-finds-oral-semaglutide-vastly-reduces-heart-attacks-strokes/">https://news.unchealthcare.org/2025/03/study-finds-oral-semaglutide-vastly-reduces-heart-attacks-strokes/</a>.
</div>
<div id="ref-uscensus2025" class="csl-entry" role="listitem">
U.S. Census Bureau. 2025. <span>“Data.census.gov: Explore Census Data.”</span> <a href="https://data.census.gov/">https://data.census.gov/</a>.
</div>
<div id="ref-medicareEligibility" class="csl-entry" role="listitem">
U.S. Department of Health &amp; Human Services. 2022. <span>“Who’s Eligible for Medicare?”</span> <a href="https://www.hhs.gov/answers/medicare-and-medicaid/who-is-eligible-for-medicare/index.html">https://www.hhs.gov/answers/medicare-and-medicaid/who-is-eligible-for-medicare/index.html</a>.
</div>
<div id="ref-fda2025ndc" class="csl-entry" role="listitem">
U.S. Food and Drug Administration. 2025. <span>“National Drug Code Directory.”</span> <a href="https://www.fda.gov/drugs/drug-approvals-and-databases/national-drug-code-directory">https://www.fda.gov/drugs/drug-approvals-and-databases/national-drug-code-directory</a>.
</div>
<div id="ref-gao2021_21_282" class="csl-entry" role="listitem">
U.S. Government Accountability Office. 2021. <span>“GAO‑21‑282: <em>Prescription Drugs - u.s. Prices for Selected Brand Drugs Were Higher on Average Then Prices in Australia, Canada, and France</em>.”</span> GAO Report GAO‑21‑282. Washington, DC: U.S. Government Accountability Office. <a href="https://www.gao.gov/products/gao-21-282">https://www.gao.gov/products/gao-21-282</a>.
</div>
<div id="ref-tidycensus2025" class="csl-entry" role="listitem">
Walker, Kyle, and Matt Herman. 2025. <em>Tidycensus: Load US Census Boundary and Attribute Data as ’Tidyverse’ and ’Sf’-Ready Data Frames</em>. <a href="https://walker-data.com/tidycensus/">https://walker-data.com/tidycensus/</a>.
</div>
</div>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    // Ensure there is a toggle, if there isn't float one in the top right
    if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
      const a = window.document.createElement('a');
      a.classList.add('top-right');
      a.classList.add('quarto-color-scheme-toggle');
      a.href = "";
      a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
      const i = window.document.createElement("i");
      i.classList.add('bi');
      a.appendChild(i);
      window.document.body.appendChild(a);
    }
    setColorSchemeToggle(hasAlternateSentinel())
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>